////
******************************************************************************
*                                                                            *
*                    ALAN Standard Library User's Manual                     *
*                                                                            *
*                      PART Library Verbs » Verbs List                       *
*                                                                            *
******************************************************************************
////

[[ch.verbs-list]]
= Verbs List

The following verbs and commands work automatically in a game that has been programmed using the library.
The synonyms and built-in syntaxes are listed in connection with each verb.
(The syntaxes show the form of the command the player must type in-game to use each verb so that the game understands it: )

// ***********
// VERBS TABLE
// ***********
// Included as DSV (Delimiter-Separated Values) file.

// @TODO: Both this table and the one in "lib_verbs.i" should be checked again
//        to ensure they are correct. We should also find a way to keep them in
//        synch, maybe via SED; the problem is that the table in "lib_verbs.i"
//        has more columns than this one, so maybe an intermediate source table
//        would required, from which to extract this one via SED.

[[table.verbs]]
.Predefined Library Verbs and Their Sytnax
[cols="m,d,d",options="header",format=dsv]
|===============================================================================
include::StdLibMan-inc_table_verbs.dsv[]
|===============================================================================


To see the outcomes for these verbs and commands, check either the file `lib_verbs.i` or `mygame_import.i` where you'll find a list of all verb outcomes.
The syntaxes of these verbs are defined in the library file `lib_verbs.i`.

Note that the `exit` and enter `verbs` won't have successful outcomes by default; after all, it is impossible to place an ACTOR (like the hero) inside a container, at least in the current version of ALAN.
To make for example the command [.play]#&gt; _enter car_# work, you should make the car a separate LOCATION and then locate the hero there at the DOES ONLY part of the enter verb in the car instance.
In other words, simulate entering and exiting by locating the hero in between locations:

[source,alan]
--------------------------------------------------------------------------------
THE driveway ISA LOCATION
  DESCRIPTION "Your house is to the north. You car is here. The street
               is to the south."
END THE.

THE inside_car ISA LOCATION AT driveway
END THE driveway.

THE car ISA OBJECT
  VERB enter
    CHECK hero NOT inside_car
      ELSE "You're inside the car already!"
    DOES ONLY
      LOCATE hero AT inside_car.
  END VERB.
END THE car.
--------------------------------------------------------------------------------

