



== Using verbs and commands

The library defines numerous verbs that can be readily used in-game with any objects or actors. For example, if you

implement

[source,alan]
--------------------------------------------------------------------------------
THE ball ISA OBJECT AT garden

END THE ball.
--------------------------------------------------------------------------------

the library enables you to

default outcomes, depending on the verb) without your having to code anything specific to make this possible.

Verb syntaxes used in the standard library

The following verbs and commands work automatically in a game that has been programmed using the library. The

synonyms and built-in syntaxes are listed in connection with each verb. (The syntaxes show the form of the

command the player must type in-game to use each verb so that the game understands it: )

// @TODO: Verbs Table
// 	Put it in an external file, maybe using CSV.
//  Find a way to keep this table in "lib_verbs.i" and include it from it?

[cols="m,d,d",options="header"]
|===============================================================================
| VERB | SYNONYMS | SYNTAX

| about
| (+ help, info)
| about


| again
| (+ g)
| again


| answer
| (+ reply)
| answer (topic)


| ask
| (+ enquire, inquire, interrogate)
| ask (act) about (topic)


| ask_for
|
| ask (act) for (obj)


| attack
| (+ beat, fight, hit, punch)
| attack (target)


| attack_with
|
| attack (target) with (weapon)


| bite
| (+ chew)
| bite (obj)


| break
| (+ destroy)
| break (obj)


| break_with
|
| break (obj) with (instr)


| brief
|
| brief


| burn
|
| burn (obj)


| burn_with
|
| burn (obj) with (instr)


| buy
| (+ purchase)
| buy (item)


| catch
|
| catch (obj)


| clean
| (+ polish, wipe)
| clean (obj)


| climb
|
| climb (obj)


| climb_on
|
| climb on (surface)


| climb_through
|
| climb through (obj)


| close
| (+ shut)
| close (obj)


| close_with
|
| close (obj) with (instr)


| consult
|
| consult (source) about (topic)


| credits
| (+ acknowledgments, author, copyright)
| credits


| cut
|
| cut (obj)


| cut_with
|
| cut (obj) with (instr)


| dance
|
| dance


| dig
|
| dig (obj)


| dive
|
| dive


| dive_in
|
| dive in (liq)


| drink
|
| drink (liq)


| drive
|
| drive (vehicle)


| drop
| (+ discard, dump, reject)
| drop (obj)


| eat
|
| eat (food)


| empty
|
| empty (obj)


| empty_in
|
| empty (obj) in (cont)


| empty_on
|
| empty (obj) on (surface)


| enter
|
| enter (obj)


| examine
| (+ check, inspect, observe, x)
| examine (obj)


| exit
|
| exit (obj)


| extinguish
| (+ put out, quench)
| extinguish (obj)


| fill
|
| fill (cont)


| fill_with
|
| fill (cont) with (substance)


| find
| (+ locate)
| find (obj)


| fire
|
| fire (weapon)


| fire_at
|
| fire (weapon) at (target)


| fix
| (+ mend, repair)
| fix (obj)


| follow
|
| follow (act)


| free
| (+ release)
| free (obj)


| get_up
|
| get up


| get_off
|
| get off (obj)


| give
|
| give (obj) to (recipient)


| go_to
|
| go to (dest)


| hint
| (+ hints)
| hint


| i
| (+ inv, inventory)
| inventory


| jump
|
| jump


| jump_in
|
| jump in (cont)


| jump_on
|
| jump on (surface)


| kick
|
| kick (target)


| kill
| (+ murder)
| kill (victim)


| kill_with
|
| kill (victim) with (weapon)


| kiss
| (+ hug, embrace)
| kiss (obj)


| knock
| (on)
| knock on (obj)


| lie_down
|
| lie down


| lie_in
|
| lie in (cont)


| lie_on
|
| lie on (surface)


| lift
|
| lift (obj)


| light
| (+ lit)
| light (obj)


| listen0
|
| listen


| listen
|
| listen to (obj)


| lock
|
| lock (obj)


| lock_with
|
| lock (obj) with (key)


| look
| (+ gaze, peek)
| look


| look_behind
|
| look behind (bulk)


| look_in
|
| look in (cont)


| look_out_of
|
| look out of (obj)


| look_through
|
| look through (bulk)


| look_under
|
| look under (bulk)


| look_up
|
| look up


| no
|
| no


| notify
| (on, off)
| notify.  notify on.  notify off


| open
|
| open (obj)


| open_with
|
| open (obj) with (instr)


| play
|
| play (obj)


| play_with
|
| play with (obj)


| pour
| (= defined at the verb 'empty')
| pour (obj)


| pour_in
| (= defined at the verb 'emtpy_in')
| pour (obj) in (cont)


| pour_on
| (= defined at the verb 'empty_on')
| pour (obj) on (surface)


| pray
|
| pray


| pry
|
| pry (obj)


| pry_with
|
| pry (obj) with (instr)


| pull
|
| pull (obj)


| push
|
| push (obj)


| push_with
|
| push (obj) with (instr)


| put
| (+ lay, place)
| put (obj)


| put_against
|
| put (obj) against (bulk))


| put_behind
|
| put (obj) behind (bulk)


| put_down
| (= defined at the verb 'drop')
| put down (obj)


| put_in
| (+ insert)
| put (obj) in (cont)


| put_near
|
| put (obj) near (bulk)


| put_on
|
| put (obj) on (surface)


| put_under
|
| put (obj) under (bulk)


| quit
| (+ q)
| quit


| read
|
| read (obj)


| remove
|
| remove (obj)


| restart
|
| restart


| restore
|
| restore


| rub
|
| rub (obj)


| save
|
| save


| say
|
| say (topic)


| say_to
|
| say (topic) to (act)


| score
|
| score


| scratch
|
| scratch (obj)


| script
|
| script.  script on.  script off.


| search
|
| search (obj)


| sell
|
| sell (item)


| shake
|
| shake (obj)


| shoot
| (at)
| shoot at (target)


| shoot_with
|
| shoot (target) with (weapon)


| shout
| (+ scream, yell)
| shout


| show
| (+ reveal)
| show (obj) to (act)


| sing
|
| sing


| sip
|
| sip (liq)


| sit
| (down)
| sit.  sit down.


| sit_on
|
| sit on (surface)


| sleep
| (+ rest)
| sleep


| smell0
|
| smell


| smell
|
| smell (odour)


| squeeze
|
| squeeze (obj)


| stand
| (up)
| stand.  stand up.


| stand_on
|
| stand on (surface)


| swim
|
| swim


| swim_in
|
| swim in (liq)


| switch
|
| switch (obj)


| switch_on
| (= defined at the verb 'turn_on')
| switch on (app)


| switch_off
| (= defined at the verb 'turn_off')
| switch off (app)


| take
| (+ carry, get, grab, hold, obtain)
| take (obj)


| take_from
| (+ remove from)
| take (obj) from (holder)


| talk
|
| talk


| talk_to
| (+ speak)
| talk to (act)


| taste
| (+ lick)
| taste (obj)


| tear
| (+ rip)
| tear (obj)


| tell
| (+ enlighten, inform)
| tell (act) about (topic)


| think
|
| think


| think_about
|
| think about (topic)


| throw
|
| throw (projectile)


| throw_at
|
| throw (projectile) at (target)


| throw_in
|
| throw (projectile) in (cont)


| throw_to
|
| throw (projectile) to (recipient)


| tie
|
| tie (obj)


| tie_to
|
| tie (obj) to (target)


| touch
| (+ feel)
| touch (obj)


| touch_with
| (+ feel)
| touch (ogg) 'with' (strum)


| turn
| (+ rotate)
| turn (obj)


| turn_on
|
| turn on (app)


| turn_off
|
| turn off (app)


| undress
|
| undress


| unlock
|
| unlock (obj)


| unlock_with
|
| unlock (obj) with (key)


| use
|
| use (obj)


| use_with
|
| use (obj) with (instr)


| verbose
|
| verbose


| wait
| (+ z)
| wait


| wear
|
| wear (obj)


| what_am_i
|
| what am i


| what_is
|
| what is (obj)


| where_am_i
|
| where am i


| where_is
|
| where is (obj)


| who_am_i
|
| who am i


| who_is
|
| who is (act)


| write
|
| write (txt) on (obj)


| yes
|
| yes
|===============================================================================



To see the outcomes for these verbs and commands, check either the file 'lib_verbs.i' or 'mygame_import.i' where

you'll find a list of all verb outcomes. The syntaxes of these verbs are defined in the library file 'lib_verbs.i'.

Note that the

ACTOR (like the

command >

DOES ONLY part of the

hero in between locations:

[source,alan]
--------------------------------------------------------------------------------
THE driveway ISA LOCATION

DESCRIPTION "Your house is to the north. You car is here. The street

is to the south."

END THE.

THE inside_car ISA LOCATION AT driveway

END THE driveway.

THE car ISA OBJECT

VERB enter

CHECK hero NOT inside_car

ELSE "You're inside the car already!"

DOES ONLY

LOCATE hero AT inside_car.

END VERB.

END THE car.
--------------------------------------------------------------------------------

The philosophy used in deciding successful and unsuccessful outcomes for action in the library

verbs

If you try the various actions in-game, with the library imported, you will notice that some actions are successful and

result in what the player commanded, while other actions do nothing (= the action is unsuccessful). For example the

response to

ending up in the location, while the response to

\[thing\]

here.

outcome for the action

Please experiment with different verbs in-game to see whether the default outcome of a particular action is suitable for

your game

more detail further below.

// PAGE 65 //



Adding alternative syntaxes for library verbs

If you wish to add flexibility to your game by allowing alternative syntaxes for certain verbs, you can do that easily in

your own game source file. Let's say that you want to for example change the syntax of the

this manual you'll find all verb syntaxes listed. From there, you'll find out that the syntax of the

talk_to = talk 'to' (act).

enabling commands like

>talk to man.

player to type

>talk man

or just

>t man

in other words, stating the character with whom you wish to talk, after the verb, without the preposition 'to'. The

easiest way to allow this is just to add an additional syntax for 'talk_to' in your own game file:

[source,alan]
--------------------------------------------------------------------------------
SYNTAX talk_to = talk (act).

talk_to = t (act).
--------------------------------------------------------------------------------

This syntax declaration should be

cancel the original syntax for 'talk_to' defined in the library; it would still be possible for the player to type >

to man

If you wish to cancel the original syntax altogether, do like this in your own game file:

[source,alan]
--------------------------------------------------------------------------------
THE my_game ISA DEFINITION BLOCK

VERB talk_to

DOES ONLY "To talk to someone, type ""talk \[person\]"" or just

""t \[person\]""."

END VERB.

END THE my_game.
--------------------------------------------------------------------------------

// PAGE 66 //



Then, outside the

[source,alan]
--------------------------------------------------------------------------------
SYNTAX my_talk_to = talk (act)

WHERE act ISA ACTOR

ELSE ...

VERB my_talk_to

DOES

IF act = mr_smith

THEN...

ELSIF...

END VERB.

SYNONYMS t = talk.
--------------------------------------------------------------------------------

b) accessing the library:

Find the verb in the library file 'lib_verbs.i' and make the desired changes to the syntax. (If you add or

change a parameter, make sure that the verb checks function properly.)

Adding your own checks for library verbs

Sometimes you might need to add an additional check to a library-defined verb. Add the check to the verb under the

my_game

[source,alan]
--------------------------------------------------------------------------------
THE soup ISA OBJECT AT kitchen

IS edible.

IS NOT hot.

VERB eat

CHECK soup IS hot

ELSE "You must warm the soup first."

END VERB.

END THE soup.
--------------------------------------------------------------------------------

Note that there is no DOES ONLY part above. The default outcome for the verb

check was passed.

// PAGE 67 //



Removing checks from library verbs

This requires accessing the library. Go to 'lib_verbs.i', find the verb you wish to remove a check from and remove the

check. (Make sure the behavior of things in your game remains sensible; the library verb checks, after all, are there to

ensure that everything functions in a reasonable and rational way.)

Overriding default responses for library verbs

Define the verb outcome with a DOES ONLY section within the

[source,alan]
--------------------------------------------------------------------------------
THE my_game ISA DEFINITION_BLOCK

VERB examine

DOES ONLY "Nothing special."

END VERB.

END THE.
--------------------------------------------------------------------------------

Making your own verbs

Declare a new verb in the normal manner instructed in the ALAN manual, outside any instances.

To create a verb that works globally and doesn't apply to any objects or actors:

[source,alan]
--------------------------------------------------------------------------------
SYNTAX test = test.

VERB test

DOES "Test successful."

END VERB.
--------------------------------------------------------------------------------

// PAGE 68 //



Here is an example of creating a verb that applies to all objects in the game:

[source,alan]
--------------------------------------------------------------------------------
SYNTAX test = test (obj)

WHERE obj ISA OBJECT

ELSE "That's not something you can test."

ADD TO EVERY OBJECT

VERB test

DOES "You test" SAY THE obj. "successfully."

END VERB.

END ADD.
--------------------------------------------------------------------------------

Restricted actions

Usually, when you need to restrict a verb from doing what it usually does (= when you want to change the default

outcome as defined by the library), you can use a

[source,alan]
--------------------------------------------------------------------------------
THE book ISA OBJECT IN table

DESCRIPTION ""

VERB examine

DOES ONLY "It's a thick, heavy book with leather covers."

END VERB.

END THE book.
--------------------------------------------------------------------------------

(Using

being shown.)

or

[source,alan]
--------------------------------------------------------------------------------
THE basement ISA ROOM

DESCRIPTION "..."

VERB jump

DOES ONLY "The ceiling is too low here."

END VERB.

END THE basement.
--------------------------------------------------------------------------------

// PAGE 69 //



(The DOES ONLY here prevents the default message for jump,

"You jump on the spot, to no avail." from being

shown.)

However, there are certain situations where you might wish to restrict the outcome for several verbs at once. Let's

imagine the hero is tied into a chair and cannot move his arms or legs. Then, actions like

still work, but actions like

way to restrict several verbs at once. Look at the list of all library-defined verbs on p. 61-. Now, there is a library-

defined attribute for each and every verb -

If you want to disable any action or actions from the start of a game, you can declare for example

[source,alan]
--------------------------------------------------------------------------------
HE my_game ISA DEFINITION_BLOCK

CAN NOT jump.

CAN NOT dance.

CAN NOT sing.

END THE my_game.
--------------------------------------------------------------------------------

and it won't be possible to jump, dance or sing in the game. The above is a shorter way to disable verbs than

[source,alan]
--------------------------------------------------------------------------------
THE my_game ISA DEFINITION_BLOCK

VERB jump

DOES ONLY "You can't do that."

END VERB.

VERB dance

DOES ONLY "You can't do that."

END VERB.

VERB sing

DOES ONLY "You can't do that."

END VERB.

END THE my_game.
--------------------------------------------------------------------------------

A list of all such attributes, corresponding to all implemented library verbs and commands, would start like this:

[source,alan]
--------------------------------------------------------------------------------
CAN about.

...

CAN 'again'.

CAN answer.

CAN ask.

CAN ask_for.

CAN attack.
--------------------------------------------------------------------------------

// PAGE 70 //



Notice how this list corresponds to the list of verbs on pp. 61-65, so it is not repeated fully here.

The outcome message for restricted verbs like the above is defined by the

instance. The default message is "You can't do that." but it can be easily edited:

[source,alan]
--------------------------------------------------------------------------------
THE my_game ISA DEFINITION_BLOCK

HAS restricted_response "That's not possible presently.".

END THE my_game.
--------------------------------------------------------------------------------

or

[source,alan]
--------------------------------------------------------------------------------
THE my_game ISA DEFINITION_BLOCK

HAS restricted_response "But you're tied up!".

END THE my_game.
--------------------------------------------------------------------------------

and so on. Now, let's again think about the situation where the hero is tied into a chair and cannot move. This kind of

situation requires disabling a rather large number of verbs:

other ones. One could do it like this:

[source,alan]
--------------------------------------------------------------------------------
EVENT tied_up

"Suddenly you're interrupted. A couple of crooks enter the room, grab hold of

you, push you into a chair, gag you and tie you into it tightly. You cannot move

your arms or legs."

MAKE my_game NOT attack.

MAKE my_game NOT attack_with.

MAKE my_game NOT bite.

MAKE my_game NOT break.

MAKE my_game NOT burn.

MAKE my_game NOT burn_with.

...

END EVENT.
--------------------------------------------------------------------------------

but we quickly understand that such a list would grow very long. That's why the library offers the option of disabling

groups of verbs at once, through a specific attribute of the

is 0. Thus the following coding would actually be unnecessary, but it is included here anyway to show the needed

formulation for this attribute:

// PAGE 71 //



[source,alan]
--------------------------------------------------------------------------------
THE my_game ISA DEFINITION_BLOCK

HAS restricted_level 0.

END THE my_game.
--------------------------------------------------------------------------------

To change the level of restriction, do for example like this:

[source,alan]
--------------------------------------------------------------------------------
SET restricted_level OF my_game TO 2.
--------------------------------------------------------------------------------

The values of this attributes work in the following way:

a)

This is the default value and it means that no verbs at all are restricted. Everything works in the normal way.

b)

This restriction can be used when the hero of the game is for example gagged, or the hero is an animal or other instance

that cannot talk.

Disabled actions: answer, ask, ask_for, say, say_to, shout, sing, tell.

Please note that the verb

disabled when the

c)

Here, verbs requiring physical action are disabled. This would be the choice to take when you want to disable verbs

when the hero is for example tied up into a chair, or under scrutiny, or in a situation where it would be awkward to try

anything drawing attention, like when listening to a lecture, or hiding. All action verbs, like

throw

"passive" action verbs like

Allowed actions: about, again, brief, credits, examine, hint, inventory, listen0, listen, look, look_at, look_behind,

look_in, look_out_of, look_through, look_under, look_up, no, notify, notify_off, notify_on, pray, quit, restart, restore,

save, score, script, script_off, script_on, smell0, smell, think, think_about, verbose, wait, what_am_i, what_is,

where_am_i, where_is, who_am_i, who_is, yes.

If you anyway want an individual action verb to work additionally, you can for example do like this:

// PAGE 72 //



[source,alan]
--------------------------------------------------------------------------------
EVENT tied_up

"Suddenly your investigations are interrupted. A couple of crooks enter the

room, grab hold of you, push you sitting on a chair and tie you into it tightly.

You cannot move your arms or legs."

SET restricted_level OF my_game TO 2.

-- all action verbs will be disabled

MAKE my_game rub.

-- but 'rub' will work

END EVENT.
--------------------------------------------------------------------------------

Then, you can for example examine, look, listen, wait etc. but also

loosen and open.

If you wish to enable communication verbs while you're tied up, you'll have to enable them individually with the

"CAN \[verb\]" method.

d)

Here, even the sensory verbs and "passive" action verbs allowed at the previous level are disabled, besides all physical

action verbs. In fact, all in-game verbs are disabled. You can't even look or examine. You can use this restriction level

when you want to for example ignore what the player typed and bring the story forward nevertheless. Only m

like

Allowed actions: about, again, brief, credits, hint, no, notify, notify_off, notify_on, quit, restart, restore, save, score,

script, script_off, script_on, verbose, yes.

Let's say that you might wish to make a game where only the

code

[source,alan]
--------------------------------------------------------------------------------
THE my_game ISA DEFINITION_BLOCK

HAS restricted_level 3.

CAN 'look'.

CAN examine.

CAN 'use'.

CAN use_with.

END THE.
--------------------------------------------------------------------------------

e)

At this level, all possible verbs, even meta verbs like

recommended to use this strict disabling of verbs, but this option is nevertheless offered for some special

circumstances. (And you can always allow a verb or two with the

Allowed actions: none.

// PAGE 73 //



This level of restriction comes in handy mostly in situations where you want to the game to ask the player about

something that has only limited alternative replies, for example

Do you want to restore a saved game (yes/no?)

>_

To only allow

(Let's imagine the question above is presented at the start of the game, before anything else happens.)

THE my_game ISA DEFINITION_BLOCK

HAS restricted_level 4.

* all possible verbs disabled

[source,alan]
--------------------------------------------------------------------------------
CAN yes. CAN 'no'.

-- but 'yes' and 'no' work

HAS restricted_response "Please answer 'yes' or 'no'."

END THE.

THE restore_room ISA LOCATION

NAME

-- no name defined for this room

DESCRIPTION "Do you want to restore a saved game (yes/no?)"

VERB yes

DOES ONLY

SET restricted_level OF my_game TO 0.

RESTORE.

END VERB.

VERB 'no'

DOES ONLY

SET restricted_level OF my_game TO 0.

LOCATE hero AT room1.

END VERB.

END THE.

THE room1 ISA LOCATION

DESCRIPTION "This is the first room of the game."

END THE.

START AT restore_room.
--------------------------------------------------------------------------------

// PAGE 74 //



Let's say for example that you want to implement the Loud Room from Zork 1. There, anything you type is repeated:

>x me

x x...

>take key

take take...

>help

help help...

>quit

quit quit...

You can achieve this by implementing

[source,alan]
--------------------------------------------------------------------------------
THE loud_room ISA ROOM

ENTERED

SET restricted_level OF my_game TO 4.

SET restricted_message OF my_game TO "\$v \$v...".

END THE.
--------------------------------------------------------------------------------

There are a couple of important things to remember with this restriction level. Firstly, the exits (

not be disabled through these attributes. You must edit the exit messages manually for each situation or location where

you restrict the allowed actions.

[source,alan]
--------------------------------------------------------------------------------
THE loud_room ISA ROOM

IS loud.

EXIT east TO corridor

CHECK loud_room IS NOT loud

ELSE "east east..."

END EXIT.

END THE.
--------------------------------------------------------------------------------

Secondly, runtime messages are triggered in the normal way (for example "You can't see any such thing.") and if you

want to also disable them in one way or another, you have to edit the messages in the

to achieve the Loud Room effect above:

[source,alan]
--------------------------------------------------------------------------------
MESSAGE NO_SUCH:

IF restricted_level OF my_game = 3

THEN "\$v \$v..."

ELSE "You can't see any such thing."

END IF.
--------------------------------------------------------------------------------

// PAGE 75 //



and the same applies to all other messages that might come into question.

NOTE: If you conjure up any verbs of your own and wish to disable them at some point in the game, you should add

a corresponding attribute to the

with the verb

[source,alan]
--------------------------------------------------------------------------------
THE my_game ISA DEFINITION_BLOCK

CAN drive.

END THE.

EVENT tied_up

"One of the thugs ties you tightly into a chair, and you cannot

move your arms or legs at all."

SET restricted_level OF my_game TO 2.

MAKE my_game NOT drive.

* 'drive' being a verb you have defined

END EVENT.
--------------------------------------------------------------------------------

You should also remember to make any self-implemented verb to work again after the restriction doesn

longer.

If you have defined a lot of verbs of your own in a game, you can do like this:

First, declare the

[source,alan]
--------------------------------------------------------------------------------
THE my_game ISA DEFINITION_BLOCK

CAN drive.

CAN recall.

CAN ride.

CAN type.

END THE.
--------------------------------------------------------------------------------

Then, define when they will be restricted:

[source,alan]
--------------------------------------------------------------------------------
WHEN restricted_level OF my_game > 1

-- three of the above are action verbs, so we restrict them

-- when the restricted_level is 2 or higher

THEN

MAKE my_game NOT drive.

MAKE my_game NOT ride.

MAKE my_game NOT type.

// PAGE 76 //



WHEN restricted_level OF my_game > 2

THEN

MAKE my_game NOT recall.

--

-- so we'll cancel it together with those verbs

only (level 3 and higher)
--------------------------------------------------------------------------------

To make these verbs work again, define:

[source,alan]
--------------------------------------------------------------------------------
MAKE my_game drive.

MAKE my_game recall.

MAKE my_game ride.

MAKE my_game type.
--------------------------------------------------------------------------------

etc.

== Adding synonyms for existing library words (verbs, object and actor classes)

Declare the synonym in your own game source file, outside any instance declarations, and outside the

instance, like this:

[source,alan]
--------------------------------------------------------------------------------
SYNONYMS peruse = read.

SYNONYMS bike = bicycle.
--------------------------------------------------------------------------------

The first word (before the equal sign) should be the new word, the second word (after the equal sign) should be the

existing one (defined elsewhere in the code).

// PAGE 77 //



== The my_game instance and its attributes

My_game

it, the game won't compile successfully. At its shortest, the needed formulation is

[source,alan]
--------------------------------------------------------------------------------
THE my_game ISA DEFINITION_BLOCK

END THE.
--------------------------------------------------------------------------------

It is called a meta-instance because everything the author defines inside it affects the whole game. The purpose of this

instance is to make it less necessary for the author to access the library files to make changes to common game

responses and messages needed in the game. That's why the instance is named

library responses and replace them with default responses that better suit the particular work in progress. The things

that the author can define within this instance are

a) default verb responses

for example "There is nothing special about the key."

b) check responses

for example "You don't have the key."

c) illegal parameter messages

for example "That's not something you can eat."

d) the implicit taking message

for example "(taking the key first)"

In addition, the author can let the game formulate automatically the game title, subtitle, author, year, and game version

at game start. This is done through attributes of the

It is also possible to for the author to implement their own custom global attributes within this instance, for example:

[source,alan]
--------------------------------------------------------------------------------
THE my_game ISA DEFINITION BLOCK

HAS tasks_left 10.

HAS treasures_found 0.

...

END THE my_game.
--------------------------------------------------------------------------------

and then check their state later, as in

[source,alan]
--------------------------------------------------------------------------------
WHEN treasures_found OF my_game = 10

THEN "Hurrah! You made it!" QUIT.
--------------------------------------------------------------------------------

// PAGE 78 //



A typical

[source,alan]
--------------------------------------------------------------------------------
THE my_game ISA DEFINITION BLOCK

HAS title "The House In The Fog".

HAS subtitle "An interactive ghost hunt".

HAS author "Xavier Y. Zamborsky".

HAS year 2018.

HAS version ″1″.

HAS enemies_defeated 0.

VERB examine

DOES ONLY "Nothing special."

END VERB.

VERB eat

CHECK hero IS hungry

ELSE "You're not hungry."

END VERB.

HAS check_obj_not_scenery_sg "That's just scenery.".

HAS check_obj_not_scenery_pl "Those are just scenery.".

HAS illegal_parameter_talk_sg "You can't possibly talk to that.".

HAS illegal_parameter_talk_pl "You can't possibly talk to those.".

END THE my_game.
--------------------------------------------------------------------------------

In the following, all the various attributes of the

1) Attributes for the start section

The following five attributes have been declared for the game start:

[source,alan]
--------------------------------------------------------------------------------
HAS title "My New Game".

HAS subtitle "".

HAS author "An ALAN Author".

HAS year 0000.

HAS version "1".
--------------------------------------------------------------------------------

If you set the version value to

version number is in quotes. This enables any kind of textual input to describe the current version, for example

version "beta0.1",

// PAGE 79 //



If the subtitle line remains an empty quote (

Now, you can modify the default attributes for example in a following way:

[source,alan]
--------------------------------------------------------------------------------
HAS title "The House In The Fog".

HAS subtitle "An interactive ghost hunt".

HAS author "Xavier Y. Zamborsky".

HAS year 2018.

HAS version "1".
--------------------------------------------------------------------------------

NOTE: In order for the banner to show up correctly, the line

[source,alan]
--------------------------------------------------------------------------------
DESCRIBE banner.
--------------------------------------------------------------------------------

needs to be added after the START AT declaration:

[source,alan]
--------------------------------------------------------------------------------
START AT bedroom.

"You knew that this evening would be different from usual when you found the

mysterious note pushed under your front door."

DESCRIBE banner.
--------------------------------------------------------------------------------

This will yield, for example:

You knew that this evening would be different from usual when you found the

mysterious note pushed under your front door.

The House In The Fog

An interactive ghost hunt

© 2017 by Xavier Y. Zamborsky

Version 1

Bedroom

>

See also example (3) at the end of this manual.

// PAGE 80 //



2) Attributes for the hero

[source,alan]
--------------------------------------------------------------------------------
HAS hero_worn_header "You are wearing"

HAS hero_worn_else "You are not wearing anything."
--------------------------------------------------------------------------------

Change these to alter the way the

for the

If the author wishes to have the CLOTHING objects worn by the

for the

[source,alan]
--------------------------------------------------------------------------------
THE hero ISA ACTOR

...

VERB examine

DOES ONLY "Blah blah..."

LIST worn.

END VERB.

END THE hero.
--------------------------------------------------------------------------------

3) Attributes for locations

HAS dark_loc_desc "It is pitch black. You can't see anything at all."

This is the default location description for dark locations. It is shown every time the hero enters a dark location or types

"LOOK" while there. Edit this to change the default description of dark locations. If/when a dark location is lighted,

this description won't be shown any longer.

[source,alan]
--------------------------------------------------------------------------------
HAS light_goes_off "It is now pitch black.".
--------------------------------------------------------------------------------

This message is shown when a light goes off and the location becomes dark.

4) Attributes for restricted actions

[source,alan]
--------------------------------------------------------------------------------
HAS restricted_response "You can't do that."
--------------------------------------------------------------------------------

If the game author restricts the outcome of any verbs in the game, this message will show instead of the usual message.

[source,alan]
--------------------------------------------------------------------------------
HAS restricted_level 0.
--------------------------------------------------------------------------------

By default, all verbs work normally, without restrictions. See further the chapter Restricted actions (p. 69-).

// PAGE 81 //



5) Illegal parameter messages

In this section, all illegal parameter messages used by the library are listed. If you wish to change any of these, you

can declare them again in the

NOTE: If you need to change a great number, or all, of these messages, for example if you're writing in another

language or you need to change the person or the tense of these messages to better suit your narrative, it is highly

recommended that you edit the file 'mygame_import.i' in the library distribution package, find the list of these

messages there, edit them, and import the 'mygame_import.i' file to your game source (together with the library).

'mygame_import.i' is a file that lists all the pre-defined attributes of the

included in the library distribution package but is not necessarily needed to run a game. It makes sense to re-declare

these messages within the

you are not satisfied with. Looking through the list of these parameter messages in 'mygame_import.i' will give you a

much better overview of them and make it easier to edit them in a uniform way to suit your purposes.

NOTE ALSO that changing illegal parameter messages is usually not the first priority of a game author and in many

cases they are left as is, as defined by the library. It is much more common to modify the standard verb outcomes or

add checks of your own to existing library checks, for example. If changing illegal parameter messages is not a high

priority for you, you might wish to skip directly to the next section.

The illegal parameter messages, as also the verb check messages and implicit taking messages further below, use the

\$ parameter naming approach.

Key to the parameter symbols used in ALAN:

\$v

the verb the player used

\$1

the first parameter the player used (for example the noun after the first verb used), without any articles, for

example

\$+1 the definite form of the first parameter the player used (for example

\$-1

the negative form of the first parameter the player used (for example

(not used in the library)

\$01

the indefinite form of the first parameter the player used (for example

\$2

etc. would be the second parameter the player used, ( for example the word

The general message for when a parameter is not suitable with the verb (for example "That's not something you can

attack"):

[source,alan]
--------------------------------------------------------------------------------
HAS illegal_parameter_sg "That's not something you can \$v.".

HAS illegal_parameter_pl "Those are not something you can \$v.".
--------------------------------------------------------------------------------

The library accounts for singular and plural cases; that

(pl) formulation.

In the following there are variations of the above message when a preposition is required after the verb (for example

"That's not something you can ask

For verbs requiring

// PAGE 82 //



[source,alan]
--------------------------------------------------------------------------------
HAS illegal_parameter_about_sg "That's not something you can \$v about.".

HAS illegal_parameter_about_pl "Those are not something you can \$v about.".
--------------------------------------------------------------------------------

There are two ditransitive verbs requiring

"throw remote control at TV")

[source,alan]
--------------------------------------------------------------------------------
HAS illegal_parameter_at "You can't \$v anything at \$2."
--------------------------------------------------------------------------------

The following is needed for the verb

[source,alan]
--------------------------------------------------------------------------------
HAS illegal_parameter_for_sg "That's not something you can \$v for.".

HAS illegal_parameter_for_pl "Those are not something you can \$v for.".
--------------------------------------------------------------------------------

The verb

[source,alan]
--------------------------------------------------------------------------------
HAS illegal_parameter_from_sg "That's not something you can take things from.

HAS illegal_parameter_from_pl "Those are not something you can take things

from.".
--------------------------------------------------------------------------------

The verbs

[source,alan]
--------------------------------------------------------------------------------
HAS illegal_parameter_in_sg "That's not something you can \$v in.".

HAS illegal_parameter_in_pl "Those are not something you can \$v in.".
--------------------------------------------------------------------------------

Climb_

[source,alan]
--------------------------------------------------------------------------------
HAS illegal_parameter_on_sg "That's not something you can \$v on.".

HAS illegal_parameter_on_pl "Those are not something you can \$v on.".
--------------------------------------------------------------------------------

For

[source,alan]
--------------------------------------------------------------------------------
HAS illegal_parameter_off_sg "That's not something you can \$v off.".

HAS illegal_parameter_off_pl "Those are not something you can \$v off.".
--------------------------------------------------------------------------------

The preposition

[source,alan]
--------------------------------------------------------------------------------
HAS illegal_parameter_to_sg "That's not something you can \$v to.".

HAS illegal_parameter_to_pl "Those are not something you can \$v to.".
--------------------------------------------------------------------------------

A slightly different message is needed for

second parameter preceded by

// PAGE 83 //



[source,alan]
--------------------------------------------------------------------------------
HAS illegal_parameter2_to_sg "That's not something you can \$v things to.".

HAS illegal_parameter2_to_pl "Those are not something you can \$v things to.".
--------------------------------------------------------------------------------

For

[source,alan]
--------------------------------------------------------------------------------
HAS illegal_parameter_with_sg "That's not something you can \$v with.".

HAS illegal_parameter_with_pl "Those are not something you can \$v with.".
--------------------------------------------------------------------------------

while a somewhat bigger group of verbs -

lock_with

'

[source,alan]
--------------------------------------------------------------------------------
HAS illegal_parameter2_with_sg "That's not something you can \$v things with.".

HAS illegal_parameter2_with_pl "Those are not something you can \$v things
with.".
--------------------------------------------------------------------------------


The communication verbs

[source,alan]
--------------------------------------------------------------------------------
HAS illegal_parameter_talk_sg "That's not something you can talk to.".

HAS illegal_parameter_talk_pl "Those are not something you can talk to.".
--------------------------------------------------------------------------------

We have a separate individual default parameter message for a handful of verbs.

For

[source,alan]
--------------------------------------------------------------------------------
HAS illegal_parameter_consult_sg "That's not something you can find

information about."
--------------------------------------------------------------------------------

[source,alan]
--------------------------------------------------------------------------------
HAS illegal_parameter_consult_pl "Those are not something you can find

information about."
--------------------------------------------------------------------------------

You'll find this message at

[source,alan]
--------------------------------------------------------------------------------
HAS illegal_parameter_examine_sg "That's not something you can examine.".

HAS illegal_parameter_examine_pl "Those are not something you can examine.".
--------------------------------------------------------------------------------

The reason why

example

// PAGE 34 //

the verb is printed in full.

The verbs

messages:

// PAGE 84 //



[source,alan]
--------------------------------------------------------------------------------
HAS illegal_parameter_look_out_sg "That's not something you can look out of.".

HAS illegal_parameter_look_out_pl "Those are not something you can look out

of.".

HAS illegal_parameter_look_through "You can't look through \$+1.".
--------------------------------------------------------------------------------

Other illegal parameter messages

The above are the default messages and their variations. There are, however, other illegal parameter messages needed

at places. They are described below.

The following message is displayed when the player tries to for example put something into an actor instance. The

verbs in which this message is found are

[source,alan]
--------------------------------------------------------------------------------
HAS illegal_parameter_act "That doesn't make sense.".
--------------------------------------------------------------------------------

The following message is displayed when the player tries to use the verbs

put_near, put_behind, put_under, throw_at, throw_in, throw_to

[source,alan]
--------------------------------------------------------------------------------
HAS illegal_parameter_obj "You can only \$v objects.".
--------------------------------------------------------------------------------

The verbs

surrounded by quotes).

[source,alan]
--------------------------------------------------------------------------------
HAS illegal_parameter_string "Please state inside double quotes ("""") what

you want to \$v.".
--------------------------------------------------------------------------------

The verbs

that is not suitable object for these verbs:

[source,alan]
--------------------------------------------------------------------------------
HAS illegal_parameter_there "It's not possible to \$v there.".
--------------------------------------------------------------------------------

The verb

[source,alan]
--------------------------------------------------------------------------------
HAS illegal_parameter_go "It's not possible to go there."
--------------------------------------------------------------------------------

The following is a variation of the above and is used when the second parameter of a ditransitive verb is not suitable.

The verbs

put_under, throw_in, throw_to, tie_to

[source,alan]
--------------------------------------------------------------------------------
HAS illegal_parameter2_there "It's not possible to \$v anything there.".
--------------------------------------------------------------------------------

// PAGE 85 //



Finally, there are some messages for the information "verbs"

below also apply to

[source,alan]
--------------------------------------------------------------------------------
HAS illegal_parameter_what_sg "That's not something I know about.".

HAS illegal_parameter_what_pl "Those are not something I know about.".

HAS illegal_parameter_who_sg "That's not somebody I know about.".

HAS illegal_parameter_who_pl "Those are not somebody I know about.".
--------------------------------------------------------------------------------

Changing the illegal parameter message of a single verb:

The way the illegal parameter messages have been defined in the library, it is not usually possible to affect just one

verb at a time. Most often, changing a default message will alter the outcome of at least a handful of verbs, because

one default message is shared by many verbs. There are some default parameter messages that only affect one verb;

you should check the list of parameter messages (above) for details. Anyway, the quickest way to accomplish this task

would be to open 'lib_verbs.i', find the verb, then modify the appropriate parameter message in its syntax statement.

6) Default verb check messages

All these check messages can be individually changed by listing them under the

file. They are also listed in the file 'mygame_import.i' in the library distribution package, for easy modification. These

check messages are used in verb definitions, mainly in 'lib_verbs.i'. Changing one check message will affect all verbs

where that particular check is found. Again, as with parameter messages, edit these messages directly in

'mygame_import.i' if you need to change a great number of them, otherwise redefine them within the

instance in your own source file. You'll quickly notice that the list is quite long, and listing any number greater than

just a few under the

a) attribute checks

The general check message for when an instance cannot be used with the verb :

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj_suitable_sg "That's not something you can \$v.".

HAS check_obj_suitable_pl "Those are not something you can \$v.".
--------------------------------------------------------------------------------

Thus, if the player tries to for example eat something that is not edible,

>eat book

That's not something you can eat.

the check message will be displayed.

// PAGE 86 //



Note that the illegal parameter messages (above) mostly report cases where the player tried to use a

instance

>take 5

That's not something you can take.

The verb

object (for example a numerical value in the above case), an illegal parameter message is shown. This restriction is

defined in the syntax of the verb. Checks, on the other hand, are used to ensure that an instance has

needed with the verb, for example

Variations of the above message, needed for example when a preposition is required after the verb, are listed below:

fire_at, throw_at, throw_to:

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj_suitable_at "You can't \$v anything at \$+2."
--------------------------------------------------------------------------------

ask_for :

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj2_suitable_for_sg "That's not something you can \$v for.".

HAS check_obj2_suitable_for_pl "Those are not something you can \$v for.".
--------------------------------------------------------------------------------

turn_off, switch_off:

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj_suitable_off_sg "That's not something you can \$v off."

HAS check_obj_suitable_off_pl "Those are not something you can \$v off.".
--------------------------------------------------------------------------------

knock, switch_on, turn_on:

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj_suitable_on_sg "That's not something you can \$v on.".

HAS check_obj_suitable_on_pl "Those are not something you can \$v on." .
--------------------------------------------------------------------------------

play_with:

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj_suitable_with_sg "That's not something you can \$v with.".

HAS check_obj_suitable_with_pl "Those are not something you can \$v with.".
--------------------------------------------------------------------------------

break_with, burn_with, close_with, cut_with, fill_with, lock_with, open_with, pry_with, push_with, touch_with,

unlock_with:

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj2_suitable_with_sg "That's not something you can \$v things
with.".


HAS check_obj2_suitable_with_pl "Those are not something you can \$v things

with.".
--------------------------------------------------------------------------------

// PAGE 87 //



Again, we have a separate message for

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj_suitable_examine_sg "That's not something you can examine.".

HAS check_obj_suitable_examine_pl "Those are not something you can examine.".

HAS check_obj_suitable_look_out_sg "That's not something you can look out

of.".

HAS check_obj_suitable_look_out_pl "Those are not something you can look out

of.".

HAS check_obj_suitable_look_through "You can't look through \$+1.".
--------------------------------------------------------------------------------

Checks for open, closed and locked objects

open, open_with:

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj_not_open_sg "\$+1 is already open.".

HAS check_obj_not_open_pl "\$+1 are already open.".
--------------------------------------------------------------------------------

close, close_with:

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj_open1_sg "\$+1 is already closed.".

HAS check_obj_open1_pl "\$+1 are already closed.".
--------------------------------------------------------------------------------

empty, empty (in/on), look_in, pour (in/on):

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj_open2_sg "You can't, since \$+1 is closed.".

HAS check_obj_open2_pl "You can't, since \$+1 are closed.".
--------------------------------------------------------------------------------

empty_in, pour_in, put_in, throw_in:

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj2_open_sg "You can't, since \$+2 is closed.".

HAS check_obj2_open_pl "You can't, since \$+2 are closed.".
--------------------------------------------------------------------------------

unlock, unlock_with:

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj_locked_sg "\$+1 is already unlocked.".

HAS check_obj_locked_pl "\$+1 are already unlocked.".
--------------------------------------------------------------------------------

lock, lock_with

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj_not_locked_sg "\$+1 is already locked.".

HAS check_obj_not_locked_pl "\$+1 are already locked.".
--------------------------------------------------------------------------------

// PAGE 88 //



Checks for "not reachable" and "distant" objects

A large number of verbs have the following checks:

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj_reachable_sg "\$+1 is out of your reach.".

HAS check_obj_reachable_pl "\$+1 are out of your reach.".

HAS check_obj_not_distant_sg "\$+1 is too far away.".

HAS check_obj_not_distant_pl "\$+1 are too far away.".
--------------------------------------------------------------------------------

In addition, the verbs

reachability of the second parameter:

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj2_reachable_sg "\$+2 is out of your reach.".

HAS check_obj2_reachable_pl "\$+2 are out of your reach.".
--------------------------------------------------------------------------------

and the verb

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj_reachable_ask "\$+1 wouldn't be able to reach \$+2.".
--------------------------------------------------------------------------------

which is triggered when the hero asks an NPC for something that the NPC cannot reach. (This happens when the object

in question has the attribute 'NOT reachable'.)

The verbs

second parameter is distant:. Thus, the way things are defined in the library, it is possible to e,g, throw something in a

container if that container is otherwise

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj2_not_distant_sg "\$+2 is too far away.".

HAS check_obj2_not_distant_pl "\$+2 are too far away.".
--------------------------------------------------------------------------------

Checks for the hero sitting or lying_down

Numerous verbs in the library have one of the following checks for sitting:
[source,alan]
--------------------------------------------------------------------------------

HAS check_hero_not_sitting1 "It is difficult to \$v while sitting down.".

HAS check_hero_not_sitting2 "It is difficult to \$v anything while sitting

down.".

HAS check_hero_not_sitting3 "It is difficult to \$v anywhere while sitting

down.".
--------------------------------------------------------------------------------

and for lying down:

[source,alan]
--------------------------------------------------------------------------------
HAS check_hero_not_lying_down1 "It is difficult to \$v while lying down.".

// PAGE 89 //



HAS check_hero_not_lying_down2 "It is difficult to \$v anything while lying

down.".

HAS check_hero_not_lying_down3 "It is difficult to \$v anywhere while lying

down.".
--------------------------------------------------------------------------------

If the player uses the verbs

HAS check_hero_not_sitting4 "You're sitting down already.".

If the player uses the verbs

displayed:

[source,alan]
--------------------------------------------------------------------------------
HAS check_hero_not_lying_down4 "You're lying down already.".
--------------------------------------------------------------------------------

Other attribute checks

Checking that the object of the action has the ability to talk; verbs

[source,alan]
--------------------------------------------------------------------------------
HAS check_act_can_talk_sg "That's not something you can talk to.".

HAS check_act_can_talk_pl "Those are not something you can talk to.".
--------------------------------------------------------------------------------

Checking that the object is allowed to be emptied/poured/put/thrown in the container

(

throw_in

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj_allowed_in_sg "\$+1 doesn't belong in \$+2".

HAS check_obj_allowed_in_pl "\$+1 don't belong in \$+2."
--------------------------------------------------------------------------------

Checking that something is broken; the verb

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj_broken_sg "That doesn't need fixing.".

HAS check_obj_broken_pl "Those don't need fixing.".
--------------------------------------------------------------------------------

Checking that the object of the action is inanimate, because normally the action would be considered improper if

done to a person:

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj_inanimate1 "\$+1 wouldn't probably appreciate that.".
--------------------------------------------------------------------------------

With some verbs, the above message is slightly altered;

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj_inanimate2 "You are not sure whether \$+1 would appreciate

that.".
--------------------------------------------------------------------------------

// PAGE 90 //



Checking if something is movable; the verbs

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj_movable "It's not possible to \$v \$+1.".
--------------------------------------------------------------------------------

Checking whether something is scenery; the verbs

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj_not_scenery_sg "\$+1 is not important.".

HAS check_obj_not_scenery_pl "\$+1 are not important.".
--------------------------------------------------------------------------------

In the verbs

be a scenery object:

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj2_not_scenery_sg "\$+2 is not important.".

HAS check_obj2_not_scenery_pl "\$+2 are not important.".
--------------------------------------------------------------------------------

For some verbs, the target of looking is checked with the following message:

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj_suitable_there "It's not possible to \$v there.".
--------------------------------------------------------------------------------

The verbs

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj2_suitable_there "It's not possible to \$v anything there.".
--------------------------------------------------------------------------------

The following check is found in verbs in which implicit taking is possible but the present instance is

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj_takeable "You don't have \$+1.".
--------------------------------------------------------------------------------

fill_with

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj2_takeable1 "You don't have \$+2.".
--------------------------------------------------------------------------------

while

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj2_takeable2 "You can't have \$+2.".
--------------------------------------------------------------------------------

Checking that an object is not too heavy (

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj_weight_sg "\$+1 is too heavy to \$v.".

HAS check_obj_weight_pl "\$+1 are too heavy to \$v.".
--------------------------------------------------------------------------------

Checking that an object can be written in/on:

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj_writeable "Nothing can be written there.".
--------------------------------------------------------------------------------

// PAGE 91 //



b) location and containment checks for actors and objects

Location and containment checks for actors other than the hero (checks for the hero are listed separately below):

For the verb

following check will verify this:

HAS check_act_near_hero "You don't quite know where \$+1 went.

You should state direction where you want to go.".

If the

triggered (

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj_in_act_sg "\$+2 doesn't have \$+1.".

HAS check_obj_in_act_pl "\$+2 don't have \$+1.".
--------------------------------------------------------------------------------

Similarly, if the player types

>give object to actor

check message is displayed:

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj_not_in_act_pl "\$+2 already have \$+1.".
HAS check_obj_not_in_act_sg "\$+2 already has \$+1.".
--------------------------------------------------------------------------------

Location and containment checks for the hero

The following checks deal with where the hero is or what (s)he is carrying.

The verb

[source,alan]
--------------------------------------------------------------------------------
HAS check_count_weapon_in_hero "You are not carrying any firearms.".
--------------------------------------------------------------------------------

find, follow, go_to, where_is:

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj_not_at_hero_sg "\$+1 is right here.".

HAS check_obj_not_at_hero_pl "\$+1 are right here.".
--------------------------------------------------------------------------------

drop, fire, fire_at, put, show:

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj_in_hero "You don't have the \$+1.".
--------------------------------------------------------------------------------

// PAGE 92 //



The following check is used in many verbs, typically ditransitive ones such as

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj2_in_hero "You don't have the \$+2.".
--------------------------------------------------------------------------------

In the following, the action tried out by the player is targeted at something the hero is holding, and the action would

not make sense (verbs

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj_not_in_hero1 "It doesn't make sense to \$v something you're
--------------------------------------------------------------------------------

holding.".

The following check ensures that the hero is not trying to get something (s)he already has (the verbs

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj_not_in_hero2 "You already have \$+1.".
--------------------------------------------------------------------------------

The throwing verbs (

to or into something that (s)he is holding:

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj2_not_in_hero1 "You are carrying \$+2.".
--------------------------------------------------------------------------------

For "putting" verbs other than

something against, behind, near, on or under something else when (s)he carries the object referenced by second

parameter (the verbs

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj2_not_in_hero2 "That would be futile.".
--------------------------------------------------------------------------------

Thus, if the

>put apple near book

wouldn't be successful.

If the

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj2_not_in_hero3 "You already have \$+2.".
--------------------------------------------------------------------------------

// PAGE 93 //



Checking whether an object is in a container or not

When the following check fires, the

contained by the object (for example if there is a bottle in a box, and the player types "empty box in bottle"). This

applies to the verbs

[source,alan]
--------------------------------------------------------------------------------
HAS check_cont_not_in_obj "That doesn't make sense.".
--------------------------------------------------------------------------------

If the

message is displayed (

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj_in_cont_sg "\$+1 is not in \$+2.".

HAS check_obj_in_cont_pl "\$+1 are not in \$+2.".
--------------------------------------------------------------------------------

If the

message is displayed

(put_in, throw_in):

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj_not_in_cont_sg "\$+1 is in \$+2 already.".

HAS check_obj_not_in_cont_pl "\$+1 are in \$+2 already.".
--------------------------------------------------------------------------------

The following check message is displayed when the

already is full of (

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj_not_in_cont2_sg "\$+1 is already full of \$+2.".

HAS check_obj_not_in_cont2_pl "\$+1 is already full of \$+2.".
--------------------------------------------------------------------------------

Checking whether an OBJECT is on a SUPPORTER or not (

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj_on_surface_sg "\$+1 is not on \$+2.".

HAS check_obj_on_surface_pl "\$+1 are not on \$+2.".
--------------------------------------------------------------------------------

Putting something on a SUPPORTER (

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj_not_on_surface_sg "\$+1 is already on \$+2.".

HAS check_obj_not_on_surface_pl "\$+1 are already on \$+2.".
--------------------------------------------------------------------------------

Checking whether an object is worn by the hero or not

You can

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj_in_worn "You are not wearing \$+1.".
--------------------------------------------------------------------------------

// PAGE 94 //



The following check is for cases when the hero tries to put on something (s)he is already wearing

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj_not_in_worn1 "You are already wearing \$+1.".
--------------------------------------------------------------------------------

Here, the action is stopped if the hero tries to attack, kick or shoot something (s)he's wearing

kick, shoot, shoot_with):

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj_not_in_worn2 "It doesn't make sense to \$v something you're
--------------------------------------------------------------------------------

wearing.".

Lastly, it's not possible to drop a piece of CLOTHING if it is worn. It will have to be removed first

HAS check_obj_not_in_worn3: "You'll have to take off \$+1 first."

c) checking location states

The following check is found in numerous verbs. It prohibits actions requiring seeing when the LOCATION is not

lit:

HAS check_current_loc_lit "It is too dark to see.".

d) logical checks

The checks in this group a) prohibit the action from being directed at the

verbs where both the first and the second parameter refer to the same instance.

1) prohibiting the action from being directed at the hero:

The following check is triggered when the player tries something like

attack_with, catch, follow, kick, listen, pull, push, push_with, take, take_from, tell)

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj_not_hero1 "It doesn't make sense to \$v yourself.".
--------------------------------------------------------------------------------

For the verbs

hero

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj_not_hero2 "There is no need to be that desperate.".
--------------------------------------------------------------------------------

For a couple of actions where the

// PAGE 95 //



This applies to the verbs

HAS check_obj_not_hero3 "That wouldn't accomplish anything.".

The verbs

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj_not_hero4 "You're right here.".
--------------------------------------------------------------------------------

If the player tries

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj_not_hero5 "You don't have to be freed.".
--------------------------------------------------------------------------------

The verbs

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj_not_hero6 "There's no time for that now.".
--------------------------------------------------------------------------------

The verb

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj_not_hero7 "Turning your head, you notice nothing unusual behind

yourself.".
--------------------------------------------------------------------------------

while

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj_not_hero8 "You notice nothing unusual under yourself.".
--------------------------------------------------------------------------------

Many ditransitive verbs have the following check when the

(say_to, show, take_from, touch_with, throw_at, throw_in, throw_to)

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj2_not_hero1 "That doesn't make sense.".
--------------------------------------------------------------------------------

Lastly, some other cases:

put_against, put_behind, put_near, put_under:

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj2_not_hero2 "That would be futile.".
--------------------------------------------------------------------------------

give, tie_to:

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj2_not_hero3 "You can't \$v things to yourself.".
--------------------------------------------------------------------------------

// PAGE 96 //



2) prohibiting the action in ditransitive verbs where both the first and the second parameter refer to the same instance:

The following checks prohibit actions like

bottle in bottle

fire_at, throw_at:

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj_not_obj2_at "It doesn't make sense to \$v something at itself.".
--------------------------------------------------------------------------------

take_from:

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj_not_obj2_from "It doesn't make sense to \$v something from
--------------------------------------------------------------------------------

itself.".

empty_in, pour_in, put_in, throw_in:

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj_not_obj2_in "It doesn't make sense to \$v something into
--------------------------------------------------------------------------------

itself.".

empty_on, pour_on, put_on:

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj_not_obj2_on "It doesn't make sense to \$v something onto
--------------------------------------------------------------------------------

itself.".

give, show, throw_to, tie_to:

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj_not_obj2_to "It doesn't make sense to \$v something to itself.".
--------------------------------------------------------------------------------

attack_with, break_with, burn_with, close_with, cut_with, fill_with , lock_with, open_with, pry_with, push_with,

shoot_with, touch_with, unlock_with, use_with:

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj_not_obj2_with "It doesn't make sense to \$v something with
itself.".
--------------------------------------------------------------------------------


put_against, put_behind, put_near, put_under:

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj_not_obj2_put "That doesn't make sense." .
--------------------------------------------------------------------------------

// PAGE 97 //



e) additional checks for classes

Lastly, there are some checks that apply only to a specific class. Most of these are found in 'lib_classes.i'.

The first one checks that a MALE character doesn't put on women's CLOTHING by default, and vice versa:

[source,alan]
--------------------------------------------------------------------------------
HAS check_clothing_sex "On second thoughts you decide \$+1 won't really suit

you.".
--------------------------------------------------------------------------------

The following check ensures that it won't be possible to put something inside a SUPPORTER object by default:

HAS check_cont_not_supporter "You can't put \$+1 inside \$+2.".

If the player tries to turn off a DEVICE that is already off, the following check is triggered (

[source,alan]
--------------------------------------------------------------------------------
HAS check_device_on_sg "\$+1 is already off.".

HAS check_device_on_pl "\$+1 are already off.".
--------------------------------------------------------------------------------

The following message is triggered if the player tries to turn on a DEVICE which is already on (

switch_on

[source,alan]
--------------------------------------------------------------------------------
HAS check_device_not_on_sg "\$+1 is already on.".

HAS check_device_not_on_pl "\$+1 are already on.".
--------------------------------------------------------------------------------

If the player tries to unlock or lock a

(

[source,alan]
--------------------------------------------------------------------------------
HAS check_door_matching_key "You can't use \$+2 to \$v \$+1.".
--------------------------------------------------------------------------------

The following message is for situations where the

lit

[source,alan]
--------------------------------------------------------------------------------
HAS check_lightsource_lit_sg "But \$+1 is not lit.".

HAS check_lightsource_lit_pl "But \$+1 are not lit.".
--------------------------------------------------------------------------------

while the following is for the opposite case

[source,alan]
--------------------------------------------------------------------------------
HAS check_lightsource_not_lit_sg "\$+1 is already lit.".

HAS check_lightsource_not_lit_pl "\$+1 are already lit.".
--------------------------------------------------------------------------------

// PAGE 98 //



Checking that the verb switch won't work with a natural LIGHTSOURCE (

[source,alan]
--------------------------------------------------------------------------------
HAS check_lightsource_switchable_sg "That's not something you can switch on

and off." .

HAS check_lightsource_switchable_pl "Those are not something you can switch on

and off.".
--------------------------------------------------------------------------------

When there is some LIQUID in a container, for example some juice in a bottle, and the player types

bottle

[source,alan]
--------------------------------------------------------------------------------
HAS check_liquid_vessel_not_cont "You can't carry \$+1 around in your bare

hands.".
--------------------------------------------------------------------------------

When the player tries to turn on a DEVICE or light a LIGHTSOURCE which is

is displayed (

[source,alan]
--------------------------------------------------------------------------------
HAS check_obj_not_broken "Nothing happens.".
--------------------------------------------------------------------------------

7) Implicit taking message

[source,alan]
--------------------------------------------------------------------------------
HAS implicit_taking_message "(taking \$+1 first)\$n".
--------------------------------------------------------------------------------

The following verbs use implicit taking:

bite, drink, eat, empty, empty_in, empty_on, give, pour, pour_in, pour_on, put_in, put_on, throw, throw_at, throw_in,

throw_to, tie_to.

(If you wish to disable automatic implicit taking for any of these verbs, you should open the library file 'lib_verbs.i',

locate the needed verbs in that file, go to their DOES sections and delete the implicit taking code. Moreover, you

should add the following check to each affected verb:

[source,alan]
--------------------------------------------------------------------------------
AND obj IN hero

ELSE "You don't have" SAY the obj. "." )
--------------------------------------------------------------------------------

// PAGE 99 //



== Have the game banner show at the start

To show the game banner at the start, after an optional intro text, you must add the text "

after the START AT clause, for example:

[source,alan]
--------------------------------------------------------------------------------
START AT room1.

DESCRIBE banner.
--------------------------------------------------------------------------------

or:

[source,alan]
--------------------------------------------------------------------------------
START AT room1.
--------------------------------------------------------------------------------

"This is the (optional) intro text at the start of the game, before the first

location description."

[source,alan]
--------------------------------------------------------------------------------
DESCRIBE banner.
--------------------------------------------------------------------------------

The following attributes should be added to the

[source,alan]
--------------------------------------------------------------------------------
HAS title "The Baffling Case Of Mrs Wells".

HAS subtitle "An interactive mystery".

HAS author "Sam".

HAS year 2017.

HAS version "1".
--------------------------------------------------------------------------------

Leaving the subtitle line out and setting the

now, these attributes would produce the following kind of banner text:

The Baffling Case Of Mrs Wells

An interactive mystery

© 2017 by Sam

Programmed with the ALAN Interactive Fiction Language v3.0

Version 1

All rights reserved

// PAGE 100 //



== Runtime messages

Many of the runtime messages built into ALAN have been altered in the library from their default wording as stated

in the ALAN manual. This is to ensure that plural is handled correctly and that there are no clashes between first and

second person. The first person of some default wordings (for example "I don't know the word "\$1") is changed to a

more passive or impersonal formulation. To edit these for your game, open 'lib_messages.i' and edit the wanted

message(s) there.

[source,alan]
--------------------------------------------------------------------------------
MESSAGE

AFTER_BUT: "You must give at least one object after '\$1'."

AGAIN: ""

BUT_ALL: "You can only use '\$1' AFTER '\$2'."

CAN_NOT_CONTAIN: "\$+1 can not contain \$+2."

CANT0: "You can't do that."

-- note that the fifth token in CANT0 is a zero, not an 'o'.

CARRIES:

IF parameter1 = hero

THEN "You are carrying"

ELSE

IF parameter1 IS NOT plural

THEN "\$+1 carries"

ELSE "\$+1 carry"

END IF.

END IF.

CONTAINMENT_LOOP:

"Putting \$+1 in"

IF parameter1 IS NOT plural

THEN "itself"

ELSE "themselves"

END IF.

"is impossible."

CONTAINMENT_LOOP2:

"Putting \$+1 in \$+2 is impossible since \$+2 already"

IF parameter2 IS NOT plural

THEN "is"

ELSE "are"

END IF.

"inside \$+1."

'CONTAINS':

IF parameter1 IS NOT plural

THEN "\$+1 contains"

ELSE "\$+1 contain"

END IF.

CONTAINS_COMMA: "\$01,"

CONTAINS_AND: "\$01 and"

CONTAINS_END: "\$01."

// PAGE 101 //



EMPTY_HANDED:

IF parameter1 = hero

THEN "You are empty-handed."

ELSE

IF parameter1 IS NOT plural

THEN "\$+1 is empty-handed."

ELSE "\$+1 are empty-handed."

END IF.

END IF.

HAVE_SCORED: "You have scored \$1 points out of \$2."

IMPOSSIBLE_WITH: "That's impossible with \$+1."

IS_EMPTY:

IF parameter1 IS NOT plural

THEN "\$+1 is empty."

ELSE "\$+1 are empty."

END IF.

MORE: "<More>"

MULTIPLE: "You can't refer to multiple objects with '\$v'."

NO_SUCH: "You can't see any \$1 here."

NO_WAY: "You can't go that way."

NOT_MUCH: "That doesn't leave much to \$v!"

NOUN: "You must supply a noun."

NOT_A_SAVEFILE: "That file does not seem to be an Alan game save

file."

QUIT_ACTION: "Do you want to RESTART, RESTORE, QUIT or UNDO? "

-- these four alternatives are hardwired to the interpreter and cannot be changed.

REALLY: "Are you sure (press ENTER to confirm)?"

RESTORE_FROM: "Enter file name to restore from"

SAVE_FAILED: "Sorry, save failed."

SAVE_MISSING: "Sorry, could not open the save file."

SAVE_NAME: "Sorry, the save file did not contain a save for this

adventure."

SAVE_OVERWRITE: "That file already exists, overwrite (y)?"

SAVE_VERSION: "Sorry, the save file was created by a different

version."

SAVE_WHERE: "Enter file name to save in"

SEE_START:

IF parameter1 IS NOT plural

THEN "There is \$01"

ELSE "There are \$01"

END IF.

SEE_COMMA: ", \$01"

SEE_AND: "and \$01"

SEE_END: "here."

NO_UNDO: "No further undo available."

UNDONE: "'\$1' undone."

UNKNOWN_WORD: "The word '\$1' is not understood."

WHAT: "That was not understood."

WHAT_WORD: "It is not clear what you mean by '\$1'."

WHICH_PRONOUN_START: "It is not clear if you by '\$1'"

// PAGE 102 //



WHICH_PRONOUN_FIRST: "mean \$+1"

WHICH_START: "It is not clear if you mean \$+1"

WHICH_COMMA: ", \$+1"

WHICH_OR: "or \$+1."
--------------------------------------------------------------------------------

== Default attributes used in the standard library

The attributes in the following list are pre-defined in the library. When you coin your own attributes for your game,

please be aware that these attributes already exist. Using any of the attributes listed below for your own purposes

doesn't necessarily cause any problems, but if problems arise, it's likely because of their being used in the library.

This attribute is added to every ENTITY:

[source,alan]
--------------------------------------------------------------------------------
NOT plural.
--------------------------------------------------------------------------------

These attributes are added to every THING:

[source,alan]
--------------------------------------------------------------------------------
IS examinable.

inanimate.

movable.

open.

reachable.

-- See also 'distant' below

takeable.

HAS allowed {null_object}.

-- You can only put an object in a container if the object

-- is in the 'allowed' set of the container.

HAS ex "".

-- an alternative to using "VERB examine DOES..."

HAS matching_key null_key.

-- All lockable objects need a matching key to lock/unlock them.

-- "null_key" is a default dummy that can be ignored.

HAS text "".

HAS weight 0.

-- Actors and objects will have different weight values, see below

NOT broken.

NOT distant.

-- Usage: you can for example talk to a "not reachable" actor but

-- not to a "distant" one.

-- You can also throw things in, to or at a not reachable target

-- but not to a distant one.

-- The other verbs where the action succeeds if the object is

-- not reachable are: dive_in, fire_at, kill_with, read, and

// PAGE 103 //



-- shoot

-- Default response for not reachable things: "The \[thing\] is out

-- of your reach."

-- Default response for distant things: "The \[thing\] is too far

-- away."

NOT drinkable.

NOT edible.

NOT fireable.

-- can (not) be used as a firearm

NOT lockable.

NOT locked.

NOT 'on'.

NOT openable.

NOT readable.

NOT scenery.

-- has special responses for 'ask_for', 'examine', 'take' and

-- 'take_from', behaves like a normal object otherwise.

NOT wearable.

NOT writeable.

CAN NOT talk.

These attributes are added to every ACTOR:

IS wearing {null_clothing}.

-- By default, actors are not described as wearing any specific

-- clothing. null_clothing is a default dummy value that can be

-- ignored.

HAS weight 50.

-- If something has the weight value of 50 or more, it cannot

-- be lifted or taken.

NOT following.

-- not following the hero character by default

NOT inanimate.

NOT named.

NOT compliant.

NOT sitting.

NOT lying_down.

The code for CLOTHING objects adds these attributes, used only internally in the library, to every actor:

IS tempcovered 0.

IS wear_flag 0.

IS sex 0.
--------------------------------------------------------------------------------

// PAGE 104 //



These attributes are added to every OBJECT:

[source,alan]
--------------------------------------------------------------------------------
HAS weight 5.

-- This is the default weight of every object, whether takeable

-- or NOT takeable. However, the library by itself

-- doesn't define any limit for containers. If the game author

-- wants to have a limit to how many objects a container can hold,

-- the author must set this limit by themselves.

Attributes added to specific classes of objects:

These attributes are added to every CLOTHING object:

IS wearable.

IS NOT donned.

-- = not worn by an NPC

IS sex 0.

IS headcover 0.

IS handscover 0.

IS feetcover 0.

IS topcover 0.

IS botcover 0.

The following attribute is defined for every DOOR object:

HAS otherside door.

The following attributes are added to every LIGHTSOURCE object:

IS natural.

IS NOT lit.

The following attribute is added to every WEAPON:

IS NOT fireable.

The following attributes are added to every LOCATION:

IS lit.

HAS visited 0.

HAS described 0.

HAS nested {nowhere}.
--------------------------------------------------------------------------------

// PAGE 105 //



The score notification coding uses the following attributes:

[source,alan]
--------------------------------------------------------------------------------
HAS oldscore 0.

IS notify_on.

IS NOT seen_notify.
--------------------------------------------------------------------------------

Finally, for restricted actions, there is an attribute defined to correspond to every library verb. (See the list on p. 61-.)

== Translating to other languages

To translate the ALAN system and library to other languages, you should

1) translate all the messages in the file 'lib_definitions.i':

* the two messages for the hero

* the two messages for dark locations

* all illegal parameter messages

* all verb check messages

* the message for implicit taking

* the message lines for the banner instance where applicable

2) translate all the "CAN \[verb\]" attributes in the file 'lib_definitions.i'.

3) translate the verb syntaxes in 'lib_verbs.i' (not parameters and the ELSE parts).

For example for the verb

[source,alan]
--------------------------------------------------------------------------------
SYNTAX attaquer = attaquer (target)

WHERE target ISA THING

ELSE

IF target IS NOT plural

THEN SAY illegal_parameter_sg OF my_game.

ELSE SAY illegal_parameter_pl OF my_game.

END IF.
--------------------------------------------------------------------------------

Also, translate the verb names, for example

[source,alan]
--------------------------------------------------------------------------------
...

VERB attaquer DOES ...
--------------------------------------------------------------------------------

4) translate the verb outcomes for class objects (what happens after DOES or DOES ONLY) in 'lib_classes.i'.

5) translate the direction names, their synonyms and the few marginal verb outcomes for indoor and outdoor objects

in 'lib_locations.i'

// PAGE 106 //



6) translate the runtime messages in 'lib_messages.i'.

Now, every possible response and message in the game is shown in the target language, and it is possible for the

player to issue commands in the target language.

It's up to the translator to decide whether to translate any of the library-defined default attributes.

== Short examples

1) A very short complete game using minimal obligatory imports and coding. Here, the hero must go from room1 north

to room2 and eat an apple to win the game.

[source,alan]
--------------------------------------------------------------------------------
IMPORT 'library.i'.

THE my_game ISA DEFINITION_BLOCK

END THE.

THE room1 ISA LOCATION

DESCRIPTION "North to room2."

EXIT north TO room2.

END THE.

THE room2 ISA LOCATION

DESCRIPTION "South to room1."

EXIT south TO room1.

END THE.

THE apple ISA OBJECT AT room2

IS edible.

VERB eat

DOES "Congratulations!" QUIT.

END VERB.

END THE.

START AT room1.

DESCRIBE banner.
--------------------------------------------------------------------------------

(This game wouldn't actually need the library at all; it would be even shorter to code:)

// PAGE 107 //



[source,alan]
--------------------------------------------------------------------------------
THE room1 ISA LOCATION

DESCRIPTION "North to room2."

EXIT north TO room2.

END THE.

THE room2 ISA LOCATION

DESCRIPTION "South to room1."

EXIT south TO room1.

END THE.

THE apple ISA OBJECT AT room2

VERB eat

DOES "Congratulations!" QUIT.

END VERB.

END THE.

START AT room1.
--------------------------------------------------------------------------------

In this latter case, though, the player wouldn't for example be able to examine him-/herself, trying to go any other

direction, take inventory, try various things with the apple, quit properly, etc.

2) Here, the player must get a candy from the kitchen and give it to a crying child in the nursery to win the game.

[source,alan]
--------------------------------------------------------------------------------
IMPORT 'library.i'.

THE my_game ISA DEFINITION_BLOCK

END THE.

THE nursery ISA ROOM

DESCRIPTION "The kitchen is to the east."

EXIT east to kitchen.

END THE.

THE child ISA PERSON AT nursery

DESCRIPTION "There is a crying child here."

VERB give

WHEN recipient

DOES ONLY

IF obj = candy

THEN "You give the candy to the child who stops

crying and starts licking it happily."

QUIT.

END IF.

END VERB.

END THE.

// PAGE 108 //



THE kitchen ISA ROOM

DESCRIPTION "You can go west, back to the nursery."

EXIT west TO nursery.

END THE.

THE table ISA SUPPORTER AT kitchen

IS NOT takeable.

END THE.

THE candy ISA OBJECT IN table

IS edible.

END THE.

START AT nursery.
--------------------------------------------------------------------------------

Examples 3-4 below show mainly different variations of the

3) In this example of defining the

'climb' and 'take_from'. In addition, the author has added a check and a response of his/her own to 'take_from':

[source,alan]
--------------------------------------------------------------------------------
THE my_game ISA DEFINITION_BLOCK

VERB eat

DOES ONLY "You don't feel like eating anything in this game."

END VERB.

VERB climb

DOES ONLY "Let's just stay on the ground, shall we?"

END VERB.

VERB take_from

WHEN obj

CHECK COUNT ISA ACTOR, AT hero = 1

-- ( = the hero himself)

ELSE "You don't want to take anything while somebody

might be looking."

DOES "Triumphantly, you fish" SAY THE obj. "out of"

SAY THE holder. "."

END VERB.

END THE.
--------------------------------------------------------------------------------

// PAGE 109 //



4) Here, the author uses the automatic formulation for the game title, author, and other information:

[source,alan]
--------------------------------------------------------------------------------
THE my_game ISA DEFINITION_BLOCK

HAS title "The Lost Treasure".

HAS subtitle "An interactive treasure hunt".

HAS author "Sam".

HAS year 2019.

HAS version "1".

END THE.

THE garden ISA LOCATION

DESCRIPTION "..."

END THE.

START AT garden.

DESCRIBE banner.
--------------------------------------------------------------------------------

5) Here, the game author has added a check of his own to the library-defined

parameter message for the verbs

[source,alan]
--------------------------------------------------------------------------------
THE my_game ISA DEFINITION_BLOCK

VERB drink

CHECK hero IS thirsty

ELSE "You don't feel like drinking anything right now."

END VERB.

HAS illegal_parameter_there "You can't \$v there.".

END THE.
--------------------------------------------------------------------------------

6) A complete example game with locked doors and keys. This code reintroduces the situation used in example 1,

with a locked door and two keys added.

[source,alan]
--------------------------------------------------------------------------------
IMPORT 'lib_classes.i'.

IMPORT 'lib_definitions.i'.

IMPORT 'lib_locations.i'.

IMPORT 'lib_messages.i'.

IMPORT 'lib_verbs.i'.

THE my_game ISA DEFINITION_BLOCK

END THE.

// PAGE 110 //



THE room1 ISA LOCATION

DESCRIPTION "North to room2."

EXIT north TO room2

CHECK locked_door_1 IS open

ELSE "The door to the north is on the way."

END EXIT.

END THE.

THE locked_door_1 ISA DOOR AT room1

DESCRIPTION ""

NAME door

HAS otherside locked_door_2.

IS lockable. IS locked.

HAS matching_key silver_key.

END THE.

THE silver_key ISA OBJECT AT room1

NAME silver key

END THE.

THE brass_key ISA OBJECT AT room1

NAME brass key

END THE.

THE room2 ISA LOCATION

DESCRIPTION "South to room1."

EXIT south TO room1

CHECK locked_door_2 IS open

ELSE "The door to the south is on the way."

END EXIT.

END THE.

THE locked_door_2 ISA DOOR AT room2

DESCRIPTION ""

NAME door

END THE.

THE apple ISA OBJECT AT room2

IS edible.

VERB eat

DOES "Congratulations!" QUIT.

END VERB.

END THE.

START AT room1.

DESCRIBE banner.
--------------------------------------------------------------------------------

// PAGE 111 //
