////
********************************************************************************
*                                                                              *
*                     ALAN Standard Library User's Manual                      *
*                                                                              *
*                          PART II — 1. Introduction                           *
*                                                                              *
********************************************************************************
////


[[ch.classes-intro]]
= Introduction

The ALAN language predefines the following eight base classes, which are the foundation of every text adventure:

[[fig.alan-classes]]
.Predefined classes in the ALAN language.
image::predefined-classes.svg[ALAN predefined classes, align="center", width='70%']

NOTE: Only the classes shown with a yellow background in the above diagram are inheritable and may be explicitly instantiated; the others (_literal_, _string_ and _integer_, with gray background) are implicitly instantiated by the player's input, when he/she types a string (text within quotes) or a digit.

WARNING: **TBD** -- Create and add a DIA diagram showing all the predefined Library classes (along with ALAN classes), using a different color to distinguish them from the hard-coded classes, and maybe use a darker color for those intermediary or internal-use classes that authors are unlikely to use (e.g. `PERSON`, `ROOM_OBJECT`, etc.).

// EOF //
