////
******************************************************************************
*                                                                            *
*                    ALAN Standard Library User's Manual                     *
*                                                                            *
*                  PART Library Verbs » Working with Verbs                   *
*                                                                            *
******************************************************************************
////


[[ch.working-with-verbs]]
= Working with Verbs

The library defines numerous verbs that can be readily used in-game with any objects or actors.
For example, if you implement

[source,alan]
------------------------------------------------------------------------------
THE ball ISA OBJECT AT garden
END THE ball.
------------------------------------------------------------------------------

the library enables you to [.play]#&gt; _examine ball_#, [.play]#&gt; _take ball_#, [.play]#&gt; _throw ball_#, [.play]#&gt; _kick ball_#, etc.
(with more or less successful default outcomes, depending on the verb) without your having to code anything specific to make this possible.


[[sec.verbs-outcomes]]
== Verbs Outcomes

If you try the various library commands, inside an adventure game, you will notice that some commands will succeed to carry out the expected action(s), while others will report a failure message, without carrying out any action.
For example, the response to [.play]#&gt; _drop [object]_# will be [.play]#Dropped.#, with the carried object being removed from the hero's inventory and placed in the location; whereas the response to [.play]#&gt; _attack [thing]_# will be [.play]#Resorting to brute force is not the solution here.#.

Which actions are allowed to succeed, and which not, is based on what is the most reasonable and expected outcome for any given action -- i.e. the outcome that game authors unlikely need to edit, except under special circumstances.

// @TODO: Add XRef to "further on in this chapter", pointing to actual section
//        dealing with verb overrides on `my_game`.

You're strongly encouraged to experiment with the different verbs, to learn whether the default outcome of a particular action is suitable for your game -- and if it isn't, redefine the outcome of that verb on the `my_game` instance.
You'll learn the details on how to achieve this further on in this chapter.

// PAGE 65 //


[[sec.alternative-syntaxes]]
== Alternative Syntaxes

If you wish to add flexibility to your game by allowing alternative syntaxes for certain verbs, you can easily do it directly in your adventure source file, without having to edit the library sources.

// @REMOVED: The following sentence was temporarily commented out, until we have
//           a proper XRef to where all verbs syntaxes can be found.
//           (most likely, the Verbs Table, but it needs to be checked first)

// Elsewhere in this manual you'll find all verb syntaxes listed.

Suppose that you wished to improve the syntax of the `talk_to` verb.
First of all, you'll need find out what the default syntax of the `talk_to` verb looks like.
You can look the verb up in the <<table.verbs,Verbs Table>> found in this manual, which provides the base syntax of each verb in a dedicated column; or you can peek inside the library source file {lib_verbs}, where are all verbs and syntaxes are defined.

In this case, the default syntax of `talk_to` is:

[source,alan, role="lib"]
------------------------------------------------------------------------------
SYNTAX talk_to = talk 'to' (act)
------------------------------------------------------------------------------

enabling commands like:

[example,role="gametranscript"]
================================================================================
&gt; _talk to man_
&gt; _talk to the teacher_
&gt; _talk to Daniel_
================================================================================


Now let's imagine that you wanted to extend the syntax so that it would be possible for the player to type:

[example,role="gametranscript"]
================================================================================
&gt; _talk man_
================================================================================


or just:

[example,role="gametranscript"]
================================================================================
&gt; _t man_
================================================================================


In other words, being able to mention the character with whom to talk, directly after the verb, without requiring the '`to`' preposition.

The easiest way to accomplish this is by providing an additional syntax for `talk_to` in your game source file:

[source,alan]
------------------------------------------------------------------------------
SYNTAX  talk_to = talk (act).
        talk_to = t (act).
------------------------------------------------------------------------------

This syntax declaration must be written outside of the `my_game` instance, in the main context of your adventure source code.
This additional syntax declaration won't replace the original syntax for `talk_to`, defined in the library; it would still be possible for the player to type [.play]#&gt; _talk to man_#, as well as using your newly defined alternative syntaxes.


== Replacing Syntaxes

Carrying on with the hypothetical `talk_to` example from the previous section, suppose you wished to replace the original syntax altogether, only allowing player to use your alternative syntax.
In order to achieve this, you'll need to carry out the following steps.

In your source adventure, suppress the action associated with the original syntax defined by the library:

[[warn.my_game-verbs]]
[WARNING]
.EDITORS' NOTE: Verbs on `my_game`
==============================================================================
We need to explain that verbs defined on `my_game` can replace the library-defined verbs because the library, during initialization of `DEFINITION_BLOCK`, nests every game location into the `my_game` location, which makes every verb on `my_game` in scope, at every location.
(See {Issue115} for more info.)

It's important that the reader is made aware of this; so we need to decide where this ought to be explained clearly, and then add cross references to it wherever the Manual mentions re-defining a verb on `my_game` as a mean to override the library's default action.
==============================================================================

[source,alan]
------------------------------------------------------------------------------
THE my_game ISA DEFINITION_BLOCK
  VERB talk_to
    DOES ONLY "To talk to someone, type ""talk [person]""
               or just ""t [person]""."
  END VERB.
END THE my_game.
------------------------------------------------------------------------------

// PAGE 66 //


Then, outside the `my_game` instance, still in your game source file, define your own _talk_ verb alternative; for example:

[source,alan]
------------------------------------------------------------------------------
SYNTAX my_talk_to = talk (act)
  WHERE act ISA ACTOR
    ELSE ...

SYNONYMS t = talk.

VERB my_talk_to
  DOES
    IF act = mr_smith
      THEN...
      ELSIF...
END VERB.
------------------------------------------------------------------------------



[[sec.adding-checks]]
== Adding CHECKs


.EDITORS' NOTE
[WARNING]
================
@CHECK ME: See <<warn.my_game-verbs,the above warning>> regarding verb-overriding on the `my_game` instance.
================


Sometimes you might need to add an additional `CHECK` to a library-defined verb.
Add the check to the verb under the `my_game` instance and not in the library file.

[source,alan]
------------------------------------------------------------------------------
THE soup ISA OBJECT AT kitchen
  IS edible.
  IS NOT hot.

  VERB eat
    CHECK soup IS hot
      ELSE "You must warm the soup first."
  END VERB.
END THE soup.
------------------------------------------------------------------------------

Note that there is no `DOES ONLY` part in the above example.
The default outcome for the `eat` verb would be carried out on the soup only if the added `CHECK` passes.

// PAGE 67 //


[[sec.removing-checks]]
== Removing CHECKs

This requires accessing the library.
Open {lib_verbs}, find the verb you wish to remove a check from, and remove the target `CHECK` block.

[CAUTION]
================
Make sure that after removing some default CHECKs the behavior of things in your game still remains coherent; after all, the default library verbs' checks are there to ensure that everything functions in a reasonable and consistent way.
================



[[sec.overriding-responses]]
== Overriding Responses


.EDITORS' NOTE
[WARNING]
================
@CHECK ME: See <<warn.my_game-verbs,the above warning>> regarding verb-overriding on the `my_game` instance.
================


Define the verb outcome with a `DOES ONLY` section within the `my_game` instance:

[source,alan]
------------------------------------------------------------------------------
THE my_game ISA DEFINITION_BLOCK
  VERB examine
    DOES ONLY "Nothing special."
  END VERB.
END THE.
------------------------------------------------------------------------------



[[sec.custom-verbs]]
== Custom Verbs

Declare a new verb in the normal manner instructed in the ALAN manual, outside any instances.

To create a verb that works globally and doesn't apply to any objects or actors:

[source,alan]
------------------------------------------------------------------------------
SYNTAX test = test.

VERB test
  DOES "Test successful."
END VERB.
------------------------------------------------------------------------------

// PAGE 68 //



Here is an example of creating a verb that applies to all objects in the game:

[source,alan]
------------------------------------------------------------------------------
SYNTAX test = test (obj)
  WHERE obj ISA OBJECT
    ELSE "That's not something you can test."

ADD TO EVERY OBJECT
  VERB test
    DOES "You test" SAY THE obj. "successfully."
  END VERB.
END ADD.
------------------------------------------------------------------------------


// EOF //
