////
********************************************************************************
*                                                                              *
*                     ALAN Standard Library User's Manual                      *
*                                                                              *
*                PART Library Attributes » Custom Descriptions                 *
*                                                                              *
********************************************************************************
////

[[ch.custom-descriptions]]
= Custom Descriptions

The library provides two ways for examining things:

. Defining a custom `VERB examine DOES ONLY` on specific instances.
. Defining the `ex` attribute string on specific instances.

As you will see, the second approach provides a quicker way to customize the description message shown when examining specific things (actors or objects); but it's only a viable solution when no extra code is required for the action.

Let's being by illustrating the first approach, i.e. the classical way of re-defining the `examine` verb on a specific instance.


.Example: Custom examine response via `VERB DOES ONLY` (from {garden1_alan})
[source,alan]
----------------------------------------
include::./garden1.alan[tag=ball_garden]
----------------------------------------


which will yield


[example,role="gametranscript"]
=======================================
include::./garden1.a3t[tag=ball_garden]
=======================================


In the example above, it was necessary to use `DOES ONLY`; if we had used `DOES` instead, the default library response for all things would be shown before the custom reponse: [.play]#You notice nothing unusual about the ball. It's a small red ball.#


Another way for examining things is to use the `ex` attribute.
`Ex` is here short for "`examine`":


.Example: Custom examine response via the `ex` attribute (from {garden2_alan})
[source,alan]
----------------------------------------
include::./garden2.alan[tag=ball_garden]
----------------------------------------


which will yield the same response as the first method:


[example,role="gametranscript"]
=======================================
include::./garden2.a3t[tag=ball_garden]
=======================================


but you notice how the needed formulation is shorter.
Which of the two methods to use is completely voluntary and up to the game author.

