////
********************************************************************************
*                                                                              *
*                     ALAN Standard Library User's Manual                      *
*                                                                              *
*                                  Chapter 1                                   *
*                                                                              *
********************************************************************************
////

[preface]
[[ch.intro]]
= Introduction

// @NOTE: We should specify the actual ALAN version that the library was tested
// 		  against (either Alpha or Beta, depending if a new Beta was released).
// 		  Some of the bug fixes that resulted from bugs discovered during tests
// 		  tests and development might require the library to use updated ALAN
// 		  releases.

This is the manual for the ALAN Standard Library v{StdLibVer}.
You'll learn how to use the library, together with the ALAN Interactive Fiction Language system v3.0, to create works of interactive fiction, also known as text adventures.

The library defines numerous verbs and commands commonly used in gameplay, such as _examine_, _take_, _drop_, _attack_, etc., along with appropriate checks and default responses to ensure they are used correctly.
It also defines various global attributes (e.g. `takeable`, `NOT openable`), as well as object and actor attributes and classes (e.g. `CLOTHING`, `WEAPON`, `PERSON`), together with illegal parameter messages (e.g. "`That's not something you can examine`").

The first official version (v1.0) of the ALAN Standard Library was published in 2010.
Before that, versions 0.x, written by Steve Griffiths, were available for use.
The writer of the current version is Anssi Räisänen.


The ALAN Standard Library v{StdLibVer} consists of the following source files:

* `library.i` -- the main library file that imports all the other modules:
** `lib_classes.i`
** `lib_definitions.i`
** `lib_locations.i`
** `lib_messages_runtime.i`
** `lib_messages_library.i`
** `lib_verbs.i`
** `lib_verbs_restrictions.i`


To import the library in your game, just add the following line to your adventure source file:

[source,alan]
--------------------------------------------------------------------------------
IMPORT 'library.i'.
--------------------------------------------------------------------------------


=== Additional Resources

In addition to library modules, the Standard Library distribution package contains some extra files, none of which are necessary for using the library:

// >>> CUSTOM ATTRIBUTES FOR ASSETS LINKS: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
// -----------------------------------------------------------------------------
// Defining these links as attributes helps to keep the list below cleaner to
// read and work on. Also, in the future we might want to defined the links
// conditionally, depending on the output backend (suppressing links in the PDF,
// or providing alternative links on the GHP ages website, etc.).
// -----------------------------------------------------------------------------
:CHANGELOG: pass:q,a[link:{StdLibDir}/CHANGELOG.html[`CHANGELOG.html`^,title="View the CHANGELOG"]]
:COPYING: pass:q,a[link:{StdLibDir}/COPYING[`COPYING`^,title="View the StdLib license file"] ]
:newgame_alan: pass:q,a[link:{ExtrasDir}/newgame.alan[`newgame.alan`^,title="Open adventure template"]]
:testgame_alan: pass:q,a[link:{ExtrasDir}/testgame.alan[`testgame.alan`^,title="Open source adventure"]]
:mygame_import: pass:q,a[link:{ExtrasDir}/mygame_import.i[`mygame_import.i`^,title="Open source file"]]
// :XXXX: pass:q,a[YYYY]
// :XXXX: pass:q,a[link:{StdLibDir}/YYYY[`YYYY`^,title="Open source adventure"]]
// <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<


// @TODO: FIX LIST OF EXTRA LIB FILES!
// [ ] Some of these files will have different extensions soon.
// [ ] Fix the direct links to those files

// @TODO: MISSING ASSETS: The`quickref.text` and `quickstart.pdf` mentioned here
// 		  are not in the StdLib repository. These docs are outdated and need to
// 		  to be edited to match StdLib v2.2.0, and possibly also be ported to
//        AsciiDoc, so their output format will probably be HTML.

[horizontal]
{CHANGELOG} :: A text file listing the changes made to the library after version v2.0.

{COPYING} :: A text file clarifying the Standard Library copyright status, its Artistic License 2.0 terms, and other legal issues regarding usage of the library in your own adventures, or creating variations of the library for public distribution.

{mygame_import} :: An auxiliary, not obligatory, definition file for the library.
If you need to edit a great number of default library messages (for verb outcomes, verb check messages etc.), you can edit this file and import it to your game project.

{newgame_alan} :: A barebones game source file defining some necessary coding when starting to write a new game.
You can use this as a starting point for a new project.

{testgame_alan} :: The source code for a test game showcasing the features of the library.

// @TEMPORARILY REMOVED: Assets that won't be included until they've been updated
//                       to the latest StdLib version, and/or ported to AsciiDoc:
////
`quickref.text`   :: A quick summary of the library features and how to use them.

`quickstart.pdf`  :: A quick summary for starting to use the library.
////

[WARNING]
============================
The _Quick Start Guide_ and _Quick Reference_ documents, which were previously distributed with the *Standard Library v2* package (files `QuickStart.docx` and `QuickRef.txt`), have been temporarily removed from the current distribution.

We're working on porting both documents (along with _The Alan Cookbook_) to AsciiDoc, in order to integrate them with the new *Standard Library* repository on GitHub, and updating their contents and examples code to mirror the latest Standard Library version.
============================



=== Where to Start

Some guidelines on how to approach reading this manual, based on your knowledge and experience of the ALAN language, or lack thereof.



==== ALAN Newbies

[big]#_Where to start if you’re a complete newbie to ALAN IF._#

If you've never programmed in ALAN before, it's advisable that you being by studying the _ALAN Manual_ (available on the ALAN website at {AlanWWW}) to get an idea of how the language works in general.
The _ALAN Manual_ described all the features of the language, whereas this manual focuses only on the features defined in the Standard Library.
After reading the _ALAN Manual_, read this manual thoroughly, with the following exceptions:

// @FIXME: dead XRef Ch???
//  	   What is now Ch.10 will be revised soon; also, the library messages have
//         been moved to 'lib_messages_library.i', so they no longer belong to the
// 		   'my_game' file/chapter:
* Read only the early part of Ch??? to get an idea of how that meta-instance is to be used in the game source.
The later passages in that chapter, listing all possible illegal parameter message attributes and verb check attributes of the `my_game` meta-instance, are meant to serve as a searchable index rather than to be read systematically.


==== Standard Library Newbies

[big]#_What to read if you're familiar with ALAN but haven't used the Standard Library_#

// @FIXME: dead XRef Ch???
Read through the whole of this library manual carefully, with the exception of Ch???, of which you should read only the early part to understand the significance of using the `my_game` meta-instance in the game source.
The latter part of that chapter, where the illegal parameter messages and other messages are listed, is meant to be read only cursorily and to be used as a searchable index when needed.


=== Typographic Conventions

The ALAN example code used in this manual follows the principle that all reserved words in the ALAN language are written in all caps:


[source,alan]
--------------------------------------------------------------------------------
THE garden ISA LOCATION
  EXIT west TO street.
END THE garden.
--------------------------------------------------------------------------------

or


[source,alan]
--------------------------------------------------------------------------------
THE cat ISA ACTOR AT street
  IS hungry.
END THE cat.
--------------------------------------------------------------------------------

This is to facilitate spotting the ALAN keywords.
Newcomers to ALAN should, however, bear in mind that the ALAN language is not case-sensitive, and one could as well write the above as


[source,alan]
--------------------------------------------------------------------------------
The garden Isa Location
  Exit west To street.
End The garden.
--------------------------------------------------------------------------------

or

[source,alan]
--------------------------------------------------------------------------------
the garden isa location
  exit west to street.
end the garden.
--------------------------------------------------------------------------------

or even

[source,alan]
--------------------------------------------------------------------------------
the garden isa location. exit west to street. end the garden.
--------------------------------------------------------------------------------

[[sec.acknowledgments]]
=== Acknowledgments

Thanks to Steve Griffiths for the score notification code snippet and for his early versions of the library, and to Alan Bampton for the code used for implementing clothing objects (layered clothing).

And, obviously, many thanks to Thomas Nilefalk and Göran Forslund for the ALAN Interactive Fiction Language.


// EOF //
