////
********************************************************************************
*                                                                              *
*                     ALAN Standard Library User's Manual                      *
*                                                                              *
*                                 Chapter 13                                   *
*                                                                              *
********************************************************************************
////


[[ch.default-attributes]]
= Default Library Attributes

The attributes in the following list are pre-defined in the library.
When you coin your own attributes for your game, please be aware that these attributes already exist.
Using any of the attributes listed below for your own purposes doesn't necessarily cause any problems, but if problems arise, it's likely because of their being used in the library.

This attribute is added to every ENTITY:

[source,alan, role="lib"]
--------------------------------------------------------------------------------
NOT plural.
--------------------------------------------------------------------------------

These attributes are added to every THING:

.Predefined `THING` attributes in {lib_definitions}.
[source,alan, role="lib"]
--------------------------------------------------------------------
include::{StdLibInc}/lib_definitions.i[tag=default-attributes-thing]
--------------------------------------------------------------------


These attributes are added to every ACTOR:

.Predefined `ACTOR` attributes in {lib_classes}.
[source,alan, role="lib"]
----------------------------------------------------------------
include::{StdLibInc}/lib_classes.i[tag=default-attributes-actor]
----------------------------------------------------------------

The code for CLOTHING objects adds these attributes, used only internally in the library, to every actor:

[source,alan, role="lib"]
--------------------------------------------------------------------------------
IS tempcovered 0.

IS wear_flag 0.

IS sex 0.
--------------------------------------------------------------------------------

// PAGE 104 //



These attributes are added to every OBJECT:

[source,alan, role="lib"]
--------------------------------------------------------------------------------
HAS weight 5.

-- This is the default weight of every object, whether takeable

-- or NOT takeable. However, the library by itself

-- doesn't define any limit for containers. If the game author

-- wants to have a limit to how many objects a container can hold,

-- the author must set this limit by themselves.
--------------------------------------------------------------------------------



== Attributes added to specific classes of objects:

These attributes are added to every CLOTHING object:

.Predefined `CLOTHING` attributes in {lib_classes}.
[source,alan, role="lib"]
-------------------------------------------------------------------
include::{StdLibInc}/lib_classes.i[tag=default-attributes-clothing]
-------------------------------------------------------------------


The following attributes are defined for every DOOR object:

.Predefined `DOOR` attributes in {lib_classes}.
[source,alan, role="lib"]
---------------------------------------------------------------
include::{StdLibInc}/lib_classes.i[tag=default-attributes-door]
---------------------------------------------------------------


The following attributes are defined for every WINDOW object:

.Predefined `WINDOW` attributes in {lib_classes}.
[source,alan, role="lib"]
-----------------------------------------------------------------
include::{StdLibInc}/lib_classes.i[tag=default-attributes-window]
-----------------------------------------------------------------


The following attributes are added to every LIGHTSOURCE object:

.Predefined `LIGHTSOURCE` attributes in {lib_classes}.
[source,alan, role="lib"]
----------------------------------------------------------------------
include::{StdLibInc}/lib_classes.i[tag=default-attributes-lightsource]
----------------------------------------------------------------------


The following attribute is added to every WEAPON:

.Predefined `WEAPON` attributes in {lib_classes}.
[source,alan, role="lib"]
-----------------------------------------------------------------
include::{StdLibInc}/lib_classes.i[tag=default-attributes-weapon]
-----------------------------------------------------------------



The following attributes are added to every LIQUID:

.Predefined `LIQUID` attributes in {lib_classes}.
[source,alan, role="lib"]
-----------------------------------------------------------------
include::{StdLibInc}/lib_classes.i[tag=default-attributes-liquid]
-----------------------------------------------------------------


The following attribute is added to every SOUND:

.Predefined `SOUND` attributes in {lib_classes}.
[source,alan, role="lib"]
----------------------------------------------------------------
include::{StdLibInc}/lib_classes.i[tag=default-attributes-sound]
----------------------------------------------------------------



The following attributes are added to every LOCATION:

[source,alan, role="lib"]
--------------------------------------------------------------------------------
IS lit.

HAS visited 0.

HAS described 0.

HAS nested {nowhere}.
--------------------------------------------------------------------------------

// PAGE 105 //



The score notification coding uses the following attributes:

[source,alan, role="lib"]
--------------------------------------------------------------------------------
HAS oldscore 0.

IS notify_on.

IS NOT seen_notify.
--------------------------------------------------------------------------------

// @FIXME: XRef to specific page (restricted actions attributes).

Finally, for every library verb there is a corresponding attribute defined in {lib_verbs_restrictions} for handling restricted actions.
(See the list on p. 61.)

// EOF //

