////
******************************************************************************
*                                                                            *
*                    ALAN Standard Library User's Manual                     *
*                                                                            *
*                     PART Library Attributes > [ misc.]                     *
*                                                                            *
******************************************************************************
////



= (NOT) distant, (NOT) reachable, scenery

Distant/NOT distant is a new attribute in v2.0 and later versions of the library.
It has been added to be used alongside with the existing reachable/NOT reachable attributes.
This has proved to be a handy distinction to have at hand.
It is possible for the hero for example to talk with an NPC (non-player character) that is NOT reachable (for example if the hero is lying down on a bed), but not with one that is distant.
Similarly, you can throw something at, to or into a NOT reachable instance (for example a basketball into a basket), but not at, to or into a distant one.
There are also some other individual cases where you can manipulate NOT reachable objects as opposed to distant ones.
The default responses for NOT reachable and distant objects are a bit different: a NOT reachable object is described to be "out of your reach" but a distant one is "too far away".
For example the library-defined ceiling object for indoor rooms is NOT reachable ("The ceiling is out of your reach") while the library-defined sky object is distant ("The sky is too far away").

[source,alan]
--------------------------------------------------------------------------------
THE sun ISA OBJECT AT outdoor
  IS distant.
END THE.
--------------------------------------------------------------------------------

(Here, the sun would be present in all outdoor locations in the game.)

In the following, some objects in the location become not reachable when the hero sits down:

[source,alan]
--------------------------------------------------------------------------------
THE bedroom ISA ROOM
  VERB sit
    DOES ONLY
      "You sit down on the chair."
      MAKE hero sitting.
      MAKE desk NOT reachable.
      MAKE wardrobe NOT reachable.
      MAKE bedroom_window NOT reachable.
  END VERB.
END THE bedroom.
--------------------------------------------------------------------------------

You can also implement on a more general level:

// PAGE 56 //



[source,alan]
--------------------------------------------------------------------------------
THE my_game ISA DEFINITION_BLOCK
  VERB sit
    DOES
      FOR EACH o ISA OBJECT, IS takeable, AT hero
        DO
          MAKE o NOT reachable.
      END FOR.
  END VERB.
END THE.
--------------------------------------------------------------------------------

Scenery objects cannot be taken or manipulated.
The default response for examining or attempting to take them is "The [object] is not important".
Asking another person for scenery objects won't have a successful result, neither does taking something from a scenery object, even if this something is not scenery.
Normal objects in scenery objects are not even mentioned by default.

[source,alan]
--------------------------------------------------------------------------------
THE livingroom ISA ROOM
END THE.

THE flowerpot ISA LISTED_CONTAINER AT livingroom
  IS scenery.
END THE.

THE ring ISA OBJECT IN flowerpot
END THE ring.
--------------------------------------------------------------------------------

[example,role="gametranscript"]
================================================================================
&gt; _x flowerpot_ +
The flowerpot is not important.

&gt; _take it_ +
The flowerpot is not important.

&gt; _ask mrs reeves for flowerpot_ +
The flowerpot is not important.
================================================================================

The ring, implemented above, is not mentioned at all, and if you, knowing about its existence only through having implemented it in the code yourself, try to take it, only the simple take verb works; take_from won't:

[example,role="gametranscript"]
================================================================================
&gt; _take ring from flowerpot_ +
The flowerpot is not important.

&gt; _take ring_ +
Taken.
================================================================================

// @CHANGED: this not was originally inside the trascript, on the right margin;
//           but it's to complex to handle formatting it.

[NOTE]
================================================================================
Note this!
If you want the player to have the ring, don't declare the flowerpot scenery.
================================================================================


// PAGE 57 //

Scenery objects are not mentioned or described by default in connection with location descriptions.

[example,role="gametranscript"]
================================================================================
&gt; _look_ +
Livingroom

&gt; _x flowerpot_ +
The flowerpot is not important.
================================================================================


You have to mention any scenery objects in the location description yourself, so that the player is aware of the existence such things in the location:


[source,alan]
--------------------------------------------------------------------------------
THE livingroom ISA ROOM
  DESCRIPTION
    "You're in a big, cozy living-room. A dinner table
     stands in the middle, surrounded by six wooden chairs.
     A lonely flowerpot stands in one of the corners."
END THE.
--------------------------------------------------------------------------------

The ring object in the above example won't get mentioned at all if it is not in the location description:

// @FIXME: Looks like part of the text was lost in the original PDF!

Note that actors can be scenery, as well.
Such actors are not mentioned in the location description by default, and examining them yields the default message "The [actor] is not important.".


// EOF //
