= The Clothing Guide
Tristano Ajmone <tajmone@gmail.com>
v1, 2018-12-16
:lang: en
// TOC Settings:
:toc: left
:toclevels: 5
// Sections Numbering:
:sectnums!:
:sectnumlevels: 2
// Cross References:
:xrefstyle: short
:section-refsig: Sect.
// Misc Settings:
:experimental: true
:icons: font
:linkattrs: true
:reproducible: true
:sectanchors:
// Highlight settings;
:source-highlighter: highlight

// *****************************************************************************
// *                                                                           *
// *                            Document Preamble                              *
// *                                                                           *
// *****************************************************************************

An introductory reference guide to using the Standard Library clothing features and undestanding the coverage attributes of the `clothing` class, and how to set their values in clothes istances.

[WARNING]
==============================================================
This document is still work in progress. To be completed soon.
==============================================================


== Introduction

The Standard Library adds some useful classes and verbs for handling clothing to allow the main character to wear and disrobe clothes in a layered manner -- i.e. to prevent putting on or removing a clothing item when a worn item of a higher layer stands in the way (e.g. wearing socks on top of shoes).

Optionally, the library also allows to assign a `sex` value to clothes, in order to prevent the main character from wearing clothes that don't match his/her own `sex` value.

This document explores these features and provides some examples on how to implement clothing in your own adventures.


== The Clothing Class

The library defines the `clothing` class for clothing items, which adds to its instances some special attributes:

[source, alan]
--------------------------
EVERY clothing ISA OBJECT

  IS wearable.

  IS sex 0. --> If not zero, restricts wearing to actors with same 'sex' value. (optional)

  -- Body coverage layered-values, by area:
  IS headcover  0. --> Head.
  IS handscover 0. --> Hands.
  IS feetcover  0. --> Feet.
  IS topcover   0. --> Chest and arms.
  IS botcover   0. --> Pelvis and legs.

  IS NOT donned.   --> Not in the 'wearing' set of any actor. (library internal use)
--------------------------

We shall now look into these attributes and how they can be used to personalize clothing in your adventures.


=== Body Coverage Attributes

By default, all new clothing instances will have all body coverage attributes set to zero.
When you create a new clothing item, you need to set its correct body coverage values according to the <<The Clothing Table,Clothing Table>> provided below.

The body coverage values of a clothing item indicate:

1. the body areas it covers,
2. the wearing layer(s) it belongs to.

The body area is indicated by the attribute name, where a value of zero indicates that the clothing item doesn't affect that area at all.
The layer of interest is indicated by the value itself, where higher values indicate higher layers (i.e. further away from the skin).
Layer values are always exponents of two (2, 4, 8, 16, 32 and 64).

Some body areas can take multiple layers of clothes, but each body layer can only be wearing one item at the time.
For example, the hero can be wearing over his chest a vest, a shirt and a sweater, for each one of them occupies a different layer in the `topcover` area (namely, 2, 8 and 16).
But he can't wear a sweater and a pullover at the same time, for they both occupy the same area and layer (`topcover 16`).

Although he might put on trousers even if he isn't wearing any underpants, he can neither put on nor remove underpants while wearing trousers, because the latter prevent access to the layer occupied by the former.
In other words, while the library doesn't impose wearing clothes on each layer, it will prevent putting on or removing clothing when another item stands in the way.

But there are smart exceptions to this rule; for example, skirts and coats.
Although a skirt occupies a higher layer than tights or panties (`botcover 32` vs `8` and `2`), the library "`knows`" that it's a special type of leg-covering clothing that (unlike trousers) doesn't prevent its wearer from putting on tights or panties.
Coats don't prevent wearing leg-covering clothing either, including trousers and skirts.

As you might have noticed, the library tries to implement a realistic approach to clothing, simulating how common cases are handled in real life.

The reference values provided in the <<The Clothing Table,Clothing Table>> are the "`secret`" behind the library smart-handling different types of clothing.
Therefore, when you create a clothing instance you can't provide just any arbitrary values, you must instead follow the examples provided in the table -- and if you don't, terrible things will happen to your adventure, and you shall regret not having followed the <<The Clothing Table,Holy Clothing Table>> in a faithful and unquestioning manner.

=== The Clothing Table

.Common Clothes Examples
[cols="<25d,5*^15m",options="header"]
|=========================================================================
| Clothing       | headcover | topcover | botcover | footcover | handcover

| hat                  |   2 |        0 |        0 |         0 |         0
| vest/bra             |   0 |        2 |        0 |         0 |         0
| undies/panties       |   0 |        0 |        2 |         0 |         0
| teddy                |   0 |        4 |        4 |         0 |         0
| blouse/shirt/T-shirt |   0 |        8 |        0 |         0 |         0
| dress/coveralls      |   0 |        8 |       32 |         0 |         0
| skirt                |   0 |        0 |       32 |         0 |         0
| trousers/shorts      |   0 |        0 |       16 |         0 |         0
| sweater/pullover     |   0 |       16 |        0 |         0 |         0
| jacket               |   0 |       32 |        0 |         0 |         0
| coat                 |   0 |       64 |       64 |         0 |         0
| socks/stockings      |   0 |        0 |        0 |         2 |         0
| tights/pantiehose    |   0 |        0 |        8 |         2 |         0
| shoes/boots          |   0 |        0 |        0 |         4 |         0
| gloves               |   0 |        0 |        0 |         0 |         2
|=========================================================================

// EOF //
